/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as ForbiddenRouteImport } from './pages/forbidden'
import { Route as adminLayoutRouteImport } from './pages/(admin)/_layout'
import { Route as adminIndexRouteImport } from './pages/(admin)/index'
import { Route as AuthLoginRouteImport } from './pages/auth/login'
import { Route as adminStaffIndexRouteImport } from './pages/(admin)/staff/index'
import { Route as adminRolesIndexRouteImport } from './pages/(admin)/roles/index'
import { Route as adminStaffAuditLogRouteImport } from './pages/(admin)/staff/audit-log'
import { Route as adminSettingsProfileRouteImport } from './pages/(admin)/settings/profile'
import { Route as adminSettingsActivityLogsRouteImport } from './pages/(admin)/settings/activity-logs'
import { Route as adminPlatformSystemRouteImport } from './pages/(admin)/platform/system'
import { Route as adminPlatformIntegrationsRouteImport } from './pages/(admin)/platform/integrations'
import { Route as adminPlatformFlagsRouteImport } from './pages/(admin)/platform/flags'
import { Route as adminPlatformExperimentsRouteImport } from './pages/(admin)/platform/experiments'
import { Route as adminOverviewOpsRouteImport } from './pages/(admin)/overview/ops'
import { Route as adminOverviewBiRouteImport } from './pages/(admin)/overview/bi'
import { Route as adminOverviewAnalyticsRouteImport } from './pages/(admin)/overview/analytics'
import { Route as adminOperationsServiceAreasRouteImport } from './pages/(admin)/operations/service-areas'
import { Route as adminLegalConfigRouteImport } from './pages/(admin)/legal/config'
import { Route as adminLegalBannersRouteImport } from './pages/(admin)/legal/banners'
import { Route as adminFinanceTaxRouteImport } from './pages/(admin)/finance/tax'
import { Route as adminFinanceRefundsRouteImport } from './pages/(admin)/finance/refunds'
import { Route as adminFinanceReconciliationRouteImport } from './pages/(admin)/finance/reconciliation'
import { Route as adminFinanceCampaignsRouteImport } from './pages/(admin)/finance/campaigns'
import { Route as adminCustomersSegmentsRouteImport } from './pages/(admin)/customers/segments'
import { Route as adminCustomersReviewsRouteImport } from './pages/(admin)/customers/reviews'
import { Route as adminCustomersReferralsRouteImport } from './pages/(admin)/customers/referrals'
import { Route as adminCustomersJourneysRouteImport } from './pages/(admin)/customers/journeys'
import { Route as adminCatalogPricingRouteImport } from './pages/(admin)/catalog/pricing'
import { Route as adminCatalogMerchandisingRouteImport } from './pages/(admin)/catalog/merchandising'
import { Route as adminCatalogCollectionsRouteImport } from './pages/(admin)/catalog/collections'
import { Route as adminOperationsOrdersIndexRouteImport } from './pages/(admin)/operations/orders/index'
import { Route as adminLegalPagesIndexRouteImport } from './pages/(admin)/legal/pages/index'
import { Route as adminFinanceSubscriptionsIndexRouteImport } from './pages/(admin)/finance/subscriptions/index'
import { Route as adminFinancePaymentsIndexRouteImport } from './pages/(admin)/finance/payments/index'
import { Route as adminFinanceCouponsIndexRouteImport } from './pages/(admin)/finance/coupons/index'
import { Route as adminCustomersBroadcastsIndexRouteImport } from './pages/(admin)/customers/broadcasts/index'
import { Route as adminCatalogVendorsIndexRouteImport } from './pages/(admin)/catalog/vendors/index'
import { Route as adminCatalogProductsIndexRouteImport } from './pages/(admin)/catalog/products/index'
import { Route as adminCatalogHubsIndexRouteImport } from './pages/(admin)/catalog/hubs/index'
import { Route as adminCatalogCategoriesIndexRouteImport } from './pages/(admin)/catalog/categories/index'
import { Route as adminCatalogBrandsIndexRouteImport } from './pages/(admin)/catalog/brands/index'
import { Route as adminPlatformUsersListRouteImport } from './pages/(admin)/platform/users/list'
import { Route as adminPlatformUsersAnalyticsRouteImport } from './pages/(admin)/platform/users/analytics'
import { Route as adminPlatformUsersActivityRouteImport } from './pages/(admin)/platform/users/activity'
import { Route as adminPlatformUsersUserIdRouteImport } from './pages/(admin)/platform/users/$userId'
import { Route as adminOperationsOrdersOrderIdRouteImport } from './pages/(admin)/operations/orders/$orderId'
import { Route as adminLegalPagesPageSlugRouteImport } from './pages/(admin)/legal/pages/$pageSlug'
import { Route as adminFinanceSubscriptionsUpcomingRouteImport } from './pages/(admin)/finance/subscriptions/upcoming'
import { Route as adminFinancePaymentsFailedRouteImport } from './pages/(admin)/finance/payments/failed'
import { Route as adminFinancePaymentsPaymentIdRouteImport } from './pages/(admin)/finance/payments/$paymentId'
import { Route as adminFinanceCouponsNewRouteImport } from './pages/(admin)/finance/coupons/new'
import { Route as adminCustomersBroadcastsNewRouteImport } from './pages/(admin)/customers/broadcasts/new'
import { Route as adminCatalogVendorsNewRouteImport } from './pages/(admin)/catalog/vendors/new'
import { Route as adminCatalogProductsNewRouteImport } from './pages/(admin)/catalog/products/new'
import { Route as adminCatalogHubsNewRouteImport } from './pages/(admin)/catalog/hubs/new'
import { Route as adminCatalogHubsMapRouteImport } from './pages/(admin)/catalog/hubs/map'
import { Route as adminCatalogCategoriesNewRouteImport } from './pages/(admin)/catalog/categories/new'
import { Route as adminCatalogCategoriesSlugRouteImport } from './pages/(admin)/catalog/categories/$slug'
import { Route as adminCatalogBrandsNewRouteImport } from './pages/(admin)/catalog/brands/new'
import { Route as adminFinanceCouponsCouponIdIndexRouteImport } from './pages/(admin)/finance/coupons/$couponId/index'
import { Route as adminCatalogVendorsVendorIdIndexRouteImport } from './pages/(admin)/catalog/vendors/$vendorId/index'
import { Route as adminCatalogHubsHubIdIndexRouteImport } from './pages/(admin)/catalog/hubs/$hubId/index'
import { Route as adminCatalogBrandsBrandIdIndexRouteImport } from './pages/(admin)/catalog/brands/$brandId/index'
import { Route as adminFinanceCouponsCouponIdEditRouteImport } from './pages/(admin)/finance/coupons/$couponId/edit'
import { Route as adminCatalogVendorsVendorIdEditRouteImport } from './pages/(admin)/catalog/vendors/$vendorId/edit'
import { Route as adminCatalogProductsProductIdEditRouteImport } from './pages/(admin)/catalog/products/$productId/edit'
import { Route as adminCatalogHubsHubIdEditRouteImport } from './pages/(admin)/catalog/hubs/$hubId/edit'
import { Route as adminCatalogBrandsBrandIdEditRouteImport } from './pages/(admin)/catalog/brands/$brandId/edit'

const ForbiddenRoute = ForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const adminLayoutRoute = adminLayoutRouteImport.update({
  id: '/(admin)',
  getParentRoute: () => rootRouteImport,
} as any)
const adminIndexRoute = adminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => adminLayoutRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const adminStaffIndexRoute = adminStaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminRolesIndexRoute = adminRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminStaffAuditLogRoute = adminStaffAuditLogRouteImport.update({
  id: '/staff/audit-log',
  path: '/staff/audit-log',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminSettingsProfileRoute = adminSettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminSettingsActivityLogsRoute =
  adminSettingsActivityLogsRouteImport.update({
    id: '/settings/activity-logs',
    path: '/settings/activity-logs',
    getParentRoute: () => adminLayoutRoute,
  } as any)
const adminPlatformSystemRoute = adminPlatformSystemRouteImport.update({
  id: '/platform/system',
  path: '/platform/system',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminPlatformIntegrationsRoute =
  adminPlatformIntegrationsRouteImport.update({
    id: '/platform/integrations',
    path: '/platform/integrations',
    getParentRoute: () => adminLayoutRoute,
  } as any)
const adminPlatformFlagsRoute = adminPlatformFlagsRouteImport.update({
  id: '/platform/flags',
  path: '/platform/flags',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminPlatformExperimentsRoute =
  adminPlatformExperimentsRouteImport.update({
    id: '/platform/experiments',
    path: '/platform/experiments',
    getParentRoute: () => adminLayoutRoute,
  } as any)
const adminOverviewOpsRoute = adminOverviewOpsRouteImport.update({
  id: '/overview/ops',
  path: '/overview/ops',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminOverviewBiRoute = adminOverviewBiRouteImport.update({
  id: '/overview/bi',
  path: '/overview/bi',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminOverviewAnalyticsRoute = adminOverviewAnalyticsRouteImport.update({
  id: '/overview/analytics',
  path: '/overview/analytics',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminOperationsServiceAreasRoute =
  adminOperationsServiceAreasRouteImport.update({
    id: '/operations/service-areas',
    path: '/operations/service-areas',
    getParentRoute: () => adminLayoutRoute,
  } as any)
const adminLegalConfigRoute = adminLegalConfigRouteImport.update({
  id: '/legal/config',
  path: '/legal/config',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminLegalBannersRoute = adminLegalBannersRouteImport.update({
  id: '/legal/banners',
  path: '/legal/banners',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminFinanceTaxRoute = adminFinanceTaxRouteImport.update({
  id: '/finance/tax',
  path: '/finance/tax',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminFinanceRefundsRoute = adminFinanceRefundsRouteImport.update({
  id: '/finance/refunds',
  path: '/finance/refunds',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminFinanceReconciliationRoute =
  adminFinanceReconciliationRouteImport.update({
    id: '/finance/reconciliation',
    path: '/finance/reconciliation',
    getParentRoute: () => adminLayoutRoute,
  } as any)
const adminFinanceCampaignsRoute = adminFinanceCampaignsRouteImport.update({
  id: '/finance/campaigns',
  path: '/finance/campaigns',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminCustomersSegmentsRoute = adminCustomersSegmentsRouteImport.update({
  id: '/customers/segments',
  path: '/customers/segments',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminCustomersReviewsRoute = adminCustomersReviewsRouteImport.update({
  id: '/customers/reviews',
  path: '/customers/reviews',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminCustomersReferralsRoute = adminCustomersReferralsRouteImport.update({
  id: '/customers/referrals',
  path: '/customers/referrals',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminCustomersJourneysRoute = adminCustomersJourneysRouteImport.update({
  id: '/customers/journeys',
  path: '/customers/journeys',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminCatalogPricingRoute = adminCatalogPricingRouteImport.update({
  id: '/catalog/pricing',
  path: '/catalog/pricing',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminCatalogMerchandisingRoute =
  adminCatalogMerchandisingRouteImport.update({
    id: '/catalog/merchandising',
    path: '/catalog/merchandising',
    getParentRoute: () => adminLayoutRoute,
  } as any)
const adminCatalogCollectionsRoute = adminCatalogCollectionsRouteImport.update({
  id: '/catalog/collections',
  path: '/catalog/collections',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminOperationsOrdersIndexRoute =
  adminOperationsOrdersIndexRouteImport.update({
    id: '/operations/orders/',
    path: '/operations/orders/',
    getParentRoute: () => adminLayoutRoute,
  } as any)
const adminLegalPagesIndexRoute = adminLegalPagesIndexRouteImport.update({
  id: '/legal/pages/',
  path: '/legal/pages/',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminFinanceSubscriptionsIndexRoute =
  adminFinanceSubscriptionsIndexRouteImport.update({
    id: '/finance/subscriptions/',
    path: '/finance/subscriptions/',
    getParentRoute: () => adminLayoutRoute,
  } as any)
const adminFinancePaymentsIndexRoute =
  adminFinancePaymentsIndexRouteImport.update({
    id: '/finance/payments/',
    path: '/finance/payments/',
    getParentRoute: () => adminLayoutRoute,
  } as any)
const adminFinanceCouponsIndexRoute =
  adminFinanceCouponsIndexRouteImport.update({
    id: '/finance/coupons/',
    path: '/finance/coupons/',
    getParentRoute: () => adminLayoutRoute,
  } as any)
const adminCustomersBroadcastsIndexRoute =
  adminCustomersBroadcastsIndexRouteImport.update({
    id: '/customers/broadcasts/',
    path: '/customers/broadcasts/',
    getParentRoute: () => adminLayoutRoute,
  } as any)
const adminCatalogVendorsIndexRoute =
  adminCatalogVendorsIndexRouteImport.update({
    id: '/catalog/vendors/',
    path: '/catalog/vendors/',
    getParentRoute: () => adminLayoutRoute,
  } as any)
const adminCatalogProductsIndexRoute =
  adminCatalogProductsIndexRouteImport.update({
    id: '/catalog/products/',
    path: '/catalog/products/',
    getParentRoute: () => adminLayoutRoute,
  } as any)
const adminCatalogHubsIndexRoute = adminCatalogHubsIndexRouteImport.update({
  id: '/catalog/hubs/',
  path: '/catalog/hubs/',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminCatalogCategoriesIndexRoute =
  adminCatalogCategoriesIndexRouteImport.update({
    id: '/catalog/categories/',
    path: '/catalog/categories/',
    getParentRoute: () => adminLayoutRoute,
  } as any)
const adminCatalogBrandsIndexRoute = adminCatalogBrandsIndexRouteImport.update({
  id: '/catalog/brands/',
  path: '/catalog/brands/',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminPlatformUsersListRoute = adminPlatformUsersListRouteImport.update({
  id: '/platform/users/list',
  path: '/platform/users/list',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminPlatformUsersAnalyticsRoute =
  adminPlatformUsersAnalyticsRouteImport.update({
    id: '/platform/users/analytics',
    path: '/platform/users/analytics',
    getParentRoute: () => adminLayoutRoute,
  } as any)
const adminPlatformUsersActivityRoute =
  adminPlatformUsersActivityRouteImport.update({
    id: '/platform/users/activity',
    path: '/platform/users/activity',
    getParentRoute: () => adminLayoutRoute,
  } as any)
const adminPlatformUsersUserIdRoute =
  adminPlatformUsersUserIdRouteImport.update({
    id: '/platform/users/$userId',
    path: '/platform/users/$userId',
    getParentRoute: () => adminLayoutRoute,
  } as any)
const adminOperationsOrdersOrderIdRoute =
  adminOperationsOrdersOrderIdRouteImport.update({
    id: '/operations/orders/$orderId',
    path: '/operations/orders/$orderId',
    getParentRoute: () => adminLayoutRoute,
  } as any)
const adminLegalPagesPageSlugRoute = adminLegalPagesPageSlugRouteImport.update({
  id: '/legal/pages/$pageSlug',
  path: '/legal/pages/$pageSlug',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminFinanceSubscriptionsUpcomingRoute =
  adminFinanceSubscriptionsUpcomingRouteImport.update({
    id: '/finance/subscriptions/upcoming',
    path: '/finance/subscriptions/upcoming',
    getParentRoute: () => adminLayoutRoute,
  } as any)
const adminFinancePaymentsFailedRoute =
  adminFinancePaymentsFailedRouteImport.update({
    id: '/finance/payments/failed',
    path: '/finance/payments/failed',
    getParentRoute: () => adminLayoutRoute,
  } as any)
const adminFinancePaymentsPaymentIdRoute =
  adminFinancePaymentsPaymentIdRouteImport.update({
    id: '/finance/payments/$paymentId',
    path: '/finance/payments/$paymentId',
    getParentRoute: () => adminLayoutRoute,
  } as any)
const adminFinanceCouponsNewRoute = adminFinanceCouponsNewRouteImport.update({
  id: '/finance/coupons/new',
  path: '/finance/coupons/new',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminCustomersBroadcastsNewRoute =
  adminCustomersBroadcastsNewRouteImport.update({
    id: '/customers/broadcasts/new',
    path: '/customers/broadcasts/new',
    getParentRoute: () => adminLayoutRoute,
  } as any)
const adminCatalogVendorsNewRoute = adminCatalogVendorsNewRouteImport.update({
  id: '/catalog/vendors/new',
  path: '/catalog/vendors/new',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminCatalogProductsNewRoute = adminCatalogProductsNewRouteImport.update({
  id: '/catalog/products/new',
  path: '/catalog/products/new',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminCatalogHubsNewRoute = adminCatalogHubsNewRouteImport.update({
  id: '/catalog/hubs/new',
  path: '/catalog/hubs/new',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminCatalogHubsMapRoute = adminCatalogHubsMapRouteImport.update({
  id: '/catalog/hubs/map',
  path: '/catalog/hubs/map',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminCatalogCategoriesNewRoute =
  adminCatalogCategoriesNewRouteImport.update({
    id: '/catalog/categories/new',
    path: '/catalog/categories/new',
    getParentRoute: () => adminLayoutRoute,
  } as any)
const adminCatalogCategoriesSlugRoute =
  adminCatalogCategoriesSlugRouteImport.update({
    id: '/catalog/categories/$slug',
    path: '/catalog/categories/$slug',
    getParentRoute: () => adminLayoutRoute,
  } as any)
const adminCatalogBrandsNewRoute = adminCatalogBrandsNewRouteImport.update({
  id: '/catalog/brands/new',
  path: '/catalog/brands/new',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminFinanceCouponsCouponIdIndexRoute =
  adminFinanceCouponsCouponIdIndexRouteImport.update({
    id: '/finance/coupons/$couponId/',
    path: '/finance/coupons/$couponId/',
    getParentRoute: () => adminLayoutRoute,
  } as any)
const adminCatalogVendorsVendorIdIndexRoute =
  adminCatalogVendorsVendorIdIndexRouteImport.update({
    id: '/catalog/vendors/$vendorId/',
    path: '/catalog/vendors/$vendorId/',
    getParentRoute: () => adminLayoutRoute,
  } as any)
const adminCatalogHubsHubIdIndexRoute =
  adminCatalogHubsHubIdIndexRouteImport.update({
    id: '/catalog/hubs/$hubId/',
    path: '/catalog/hubs/$hubId/',
    getParentRoute: () => adminLayoutRoute,
  } as any)
const adminCatalogBrandsBrandIdIndexRoute =
  adminCatalogBrandsBrandIdIndexRouteImport.update({
    id: '/catalog/brands/$brandId/',
    path: '/catalog/brands/$brandId/',
    getParentRoute: () => adminLayoutRoute,
  } as any)
const adminFinanceCouponsCouponIdEditRoute =
  adminFinanceCouponsCouponIdEditRouteImport.update({
    id: '/finance/coupons/$couponId/edit',
    path: '/finance/coupons/$couponId/edit',
    getParentRoute: () => adminLayoutRoute,
  } as any)
const adminCatalogVendorsVendorIdEditRoute =
  adminCatalogVendorsVendorIdEditRouteImport.update({
    id: '/catalog/vendors/$vendorId/edit',
    path: '/catalog/vendors/$vendorId/edit',
    getParentRoute: () => adminLayoutRoute,
  } as any)
const adminCatalogProductsProductIdEditRoute =
  adminCatalogProductsProductIdEditRouteImport.update({
    id: '/catalog/products/$productId/edit',
    path: '/catalog/products/$productId/edit',
    getParentRoute: () => adminLayoutRoute,
  } as any)
const adminCatalogHubsHubIdEditRoute =
  adminCatalogHubsHubIdEditRouteImport.update({
    id: '/catalog/hubs/$hubId/edit',
    path: '/catalog/hubs/$hubId/edit',
    getParentRoute: () => adminLayoutRoute,
  } as any)
const adminCatalogBrandsBrandIdEditRoute =
  adminCatalogBrandsBrandIdEditRouteImport.update({
    id: '/catalog/brands/$brandId/edit',
    path: '/catalog/brands/$brandId/edit',
    getParentRoute: () => adminLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/forbidden': typeof ForbiddenRoute
  '/auth/login': typeof AuthLoginRoute
  '/': typeof adminIndexRoute
  '/catalog/collections': typeof adminCatalogCollectionsRoute
  '/catalog/merchandising': typeof adminCatalogMerchandisingRoute
  '/catalog/pricing': typeof adminCatalogPricingRoute
  '/customers/journeys': typeof adminCustomersJourneysRoute
  '/customers/referrals': typeof adminCustomersReferralsRoute
  '/customers/reviews': typeof adminCustomersReviewsRoute
  '/customers/segments': typeof adminCustomersSegmentsRoute
  '/finance/campaigns': typeof adminFinanceCampaignsRoute
  '/finance/reconciliation': typeof adminFinanceReconciliationRoute
  '/finance/refunds': typeof adminFinanceRefundsRoute
  '/finance/tax': typeof adminFinanceTaxRoute
  '/legal/banners': typeof adminLegalBannersRoute
  '/legal/config': typeof adminLegalConfigRoute
  '/operations/service-areas': typeof adminOperationsServiceAreasRoute
  '/overview/analytics': typeof adminOverviewAnalyticsRoute
  '/overview/bi': typeof adminOverviewBiRoute
  '/overview/ops': typeof adminOverviewOpsRoute
  '/platform/experiments': typeof adminPlatformExperimentsRoute
  '/platform/flags': typeof adminPlatformFlagsRoute
  '/platform/integrations': typeof adminPlatformIntegrationsRoute
  '/platform/system': typeof adminPlatformSystemRoute
  '/settings/activity-logs': typeof adminSettingsActivityLogsRoute
  '/settings/profile': typeof adminSettingsProfileRoute
  '/staff/audit-log': typeof adminStaffAuditLogRoute
  '/roles/': typeof adminRolesIndexRoute
  '/staff/': typeof adminStaffIndexRoute
  '/catalog/brands/new': typeof adminCatalogBrandsNewRoute
  '/catalog/categories/$slug': typeof adminCatalogCategoriesSlugRoute
  '/catalog/categories/new': typeof adminCatalogCategoriesNewRoute
  '/catalog/hubs/map': typeof adminCatalogHubsMapRoute
  '/catalog/hubs/new': typeof adminCatalogHubsNewRoute
  '/catalog/products/new': typeof adminCatalogProductsNewRoute
  '/catalog/vendors/new': typeof adminCatalogVendorsNewRoute
  '/customers/broadcasts/new': typeof adminCustomersBroadcastsNewRoute
  '/finance/coupons/new': typeof adminFinanceCouponsNewRoute
  '/finance/payments/$paymentId': typeof adminFinancePaymentsPaymentIdRoute
  '/finance/payments/failed': typeof adminFinancePaymentsFailedRoute
  '/finance/subscriptions/upcoming': typeof adminFinanceSubscriptionsUpcomingRoute
  '/legal/pages/$pageSlug': typeof adminLegalPagesPageSlugRoute
  '/operations/orders/$orderId': typeof adminOperationsOrdersOrderIdRoute
  '/platform/users/$userId': typeof adminPlatformUsersUserIdRoute
  '/platform/users/activity': typeof adminPlatformUsersActivityRoute
  '/platform/users/analytics': typeof adminPlatformUsersAnalyticsRoute
  '/platform/users/list': typeof adminPlatformUsersListRoute
  '/catalog/brands/': typeof adminCatalogBrandsIndexRoute
  '/catalog/categories/': typeof adminCatalogCategoriesIndexRoute
  '/catalog/hubs/': typeof adminCatalogHubsIndexRoute
  '/catalog/products/': typeof adminCatalogProductsIndexRoute
  '/catalog/vendors/': typeof adminCatalogVendorsIndexRoute
  '/customers/broadcasts/': typeof adminCustomersBroadcastsIndexRoute
  '/finance/coupons/': typeof adminFinanceCouponsIndexRoute
  '/finance/payments/': typeof adminFinancePaymentsIndexRoute
  '/finance/subscriptions/': typeof adminFinanceSubscriptionsIndexRoute
  '/legal/pages/': typeof adminLegalPagesIndexRoute
  '/operations/orders/': typeof adminOperationsOrdersIndexRoute
  '/catalog/brands/$brandId/edit': typeof adminCatalogBrandsBrandIdEditRoute
  '/catalog/hubs/$hubId/edit': typeof adminCatalogHubsHubIdEditRoute
  '/catalog/products/$productId/edit': typeof adminCatalogProductsProductIdEditRoute
  '/catalog/vendors/$vendorId/edit': typeof adminCatalogVendorsVendorIdEditRoute
  '/finance/coupons/$couponId/edit': typeof adminFinanceCouponsCouponIdEditRoute
  '/catalog/brands/$brandId/': typeof adminCatalogBrandsBrandIdIndexRoute
  '/catalog/hubs/$hubId/': typeof adminCatalogHubsHubIdIndexRoute
  '/catalog/vendors/$vendorId/': typeof adminCatalogVendorsVendorIdIndexRoute
  '/finance/coupons/$couponId/': typeof adminFinanceCouponsCouponIdIndexRoute
}
export interface FileRoutesByTo {
  '/forbidden': typeof ForbiddenRoute
  '/auth/login': typeof AuthLoginRoute
  '/': typeof adminIndexRoute
  '/catalog/collections': typeof adminCatalogCollectionsRoute
  '/catalog/merchandising': typeof adminCatalogMerchandisingRoute
  '/catalog/pricing': typeof adminCatalogPricingRoute
  '/customers/journeys': typeof adminCustomersJourneysRoute
  '/customers/referrals': typeof adminCustomersReferralsRoute
  '/customers/reviews': typeof adminCustomersReviewsRoute
  '/customers/segments': typeof adminCustomersSegmentsRoute
  '/finance/campaigns': typeof adminFinanceCampaignsRoute
  '/finance/reconciliation': typeof adminFinanceReconciliationRoute
  '/finance/refunds': typeof adminFinanceRefundsRoute
  '/finance/tax': typeof adminFinanceTaxRoute
  '/legal/banners': typeof adminLegalBannersRoute
  '/legal/config': typeof adminLegalConfigRoute
  '/operations/service-areas': typeof adminOperationsServiceAreasRoute
  '/overview/analytics': typeof adminOverviewAnalyticsRoute
  '/overview/bi': typeof adminOverviewBiRoute
  '/overview/ops': typeof adminOverviewOpsRoute
  '/platform/experiments': typeof adminPlatformExperimentsRoute
  '/platform/flags': typeof adminPlatformFlagsRoute
  '/platform/integrations': typeof adminPlatformIntegrationsRoute
  '/platform/system': typeof adminPlatformSystemRoute
  '/settings/activity-logs': typeof adminSettingsActivityLogsRoute
  '/settings/profile': typeof adminSettingsProfileRoute
  '/staff/audit-log': typeof adminStaffAuditLogRoute
  '/roles': typeof adminRolesIndexRoute
  '/staff': typeof adminStaffIndexRoute
  '/catalog/brands/new': typeof adminCatalogBrandsNewRoute
  '/catalog/categories/$slug': typeof adminCatalogCategoriesSlugRoute
  '/catalog/categories/new': typeof adminCatalogCategoriesNewRoute
  '/catalog/hubs/map': typeof adminCatalogHubsMapRoute
  '/catalog/hubs/new': typeof adminCatalogHubsNewRoute
  '/catalog/products/new': typeof adminCatalogProductsNewRoute
  '/catalog/vendors/new': typeof adminCatalogVendorsNewRoute
  '/customers/broadcasts/new': typeof adminCustomersBroadcastsNewRoute
  '/finance/coupons/new': typeof adminFinanceCouponsNewRoute
  '/finance/payments/$paymentId': typeof adminFinancePaymentsPaymentIdRoute
  '/finance/payments/failed': typeof adminFinancePaymentsFailedRoute
  '/finance/subscriptions/upcoming': typeof adminFinanceSubscriptionsUpcomingRoute
  '/legal/pages/$pageSlug': typeof adminLegalPagesPageSlugRoute
  '/operations/orders/$orderId': typeof adminOperationsOrdersOrderIdRoute
  '/platform/users/$userId': typeof adminPlatformUsersUserIdRoute
  '/platform/users/activity': typeof adminPlatformUsersActivityRoute
  '/platform/users/analytics': typeof adminPlatformUsersAnalyticsRoute
  '/platform/users/list': typeof adminPlatformUsersListRoute
  '/catalog/brands': typeof adminCatalogBrandsIndexRoute
  '/catalog/categories': typeof adminCatalogCategoriesIndexRoute
  '/catalog/hubs': typeof adminCatalogHubsIndexRoute
  '/catalog/products': typeof adminCatalogProductsIndexRoute
  '/catalog/vendors': typeof adminCatalogVendorsIndexRoute
  '/customers/broadcasts': typeof adminCustomersBroadcastsIndexRoute
  '/finance/coupons': typeof adminFinanceCouponsIndexRoute
  '/finance/payments': typeof adminFinancePaymentsIndexRoute
  '/finance/subscriptions': typeof adminFinanceSubscriptionsIndexRoute
  '/legal/pages': typeof adminLegalPagesIndexRoute
  '/operations/orders': typeof adminOperationsOrdersIndexRoute
  '/catalog/brands/$brandId/edit': typeof adminCatalogBrandsBrandIdEditRoute
  '/catalog/hubs/$hubId/edit': typeof adminCatalogHubsHubIdEditRoute
  '/catalog/products/$productId/edit': typeof adminCatalogProductsProductIdEditRoute
  '/catalog/vendors/$vendorId/edit': typeof adminCatalogVendorsVendorIdEditRoute
  '/finance/coupons/$couponId/edit': typeof adminFinanceCouponsCouponIdEditRoute
  '/catalog/brands/$brandId': typeof adminCatalogBrandsBrandIdIndexRoute
  '/catalog/hubs/$hubId': typeof adminCatalogHubsHubIdIndexRoute
  '/catalog/vendors/$vendorId': typeof adminCatalogVendorsVendorIdIndexRoute
  '/finance/coupons/$couponId': typeof adminFinanceCouponsCouponIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(admin)': typeof adminLayoutRouteWithChildren
  '/forbidden': typeof ForbiddenRoute
  '/auth/login': typeof AuthLoginRoute
  '/(admin)/': typeof adminIndexRoute
  '/(admin)/catalog/collections': typeof adminCatalogCollectionsRoute
  '/(admin)/catalog/merchandising': typeof adminCatalogMerchandisingRoute
  '/(admin)/catalog/pricing': typeof adminCatalogPricingRoute
  '/(admin)/customers/journeys': typeof adminCustomersJourneysRoute
  '/(admin)/customers/referrals': typeof adminCustomersReferralsRoute
  '/(admin)/customers/reviews': typeof adminCustomersReviewsRoute
  '/(admin)/customers/segments': typeof adminCustomersSegmentsRoute
  '/(admin)/finance/campaigns': typeof adminFinanceCampaignsRoute
  '/(admin)/finance/reconciliation': typeof adminFinanceReconciliationRoute
  '/(admin)/finance/refunds': typeof adminFinanceRefundsRoute
  '/(admin)/finance/tax': typeof adminFinanceTaxRoute
  '/(admin)/legal/banners': typeof adminLegalBannersRoute
  '/(admin)/legal/config': typeof adminLegalConfigRoute
  '/(admin)/operations/service-areas': typeof adminOperationsServiceAreasRoute
  '/(admin)/overview/analytics': typeof adminOverviewAnalyticsRoute
  '/(admin)/overview/bi': typeof adminOverviewBiRoute
  '/(admin)/overview/ops': typeof adminOverviewOpsRoute
  '/(admin)/platform/experiments': typeof adminPlatformExperimentsRoute
  '/(admin)/platform/flags': typeof adminPlatformFlagsRoute
  '/(admin)/platform/integrations': typeof adminPlatformIntegrationsRoute
  '/(admin)/platform/system': typeof adminPlatformSystemRoute
  '/(admin)/settings/activity-logs': typeof adminSettingsActivityLogsRoute
  '/(admin)/settings/profile': typeof adminSettingsProfileRoute
  '/(admin)/staff/audit-log': typeof adminStaffAuditLogRoute
  '/(admin)/roles/': typeof adminRolesIndexRoute
  '/(admin)/staff/': typeof adminStaffIndexRoute
  '/(admin)/catalog/brands/new': typeof adminCatalogBrandsNewRoute
  '/(admin)/catalog/categories/$slug': typeof adminCatalogCategoriesSlugRoute
  '/(admin)/catalog/categories/new': typeof adminCatalogCategoriesNewRoute
  '/(admin)/catalog/hubs/map': typeof adminCatalogHubsMapRoute
  '/(admin)/catalog/hubs/new': typeof adminCatalogHubsNewRoute
  '/(admin)/catalog/products/new': typeof adminCatalogProductsNewRoute
  '/(admin)/catalog/vendors/new': typeof adminCatalogVendorsNewRoute
  '/(admin)/customers/broadcasts/new': typeof adminCustomersBroadcastsNewRoute
  '/(admin)/finance/coupons/new': typeof adminFinanceCouponsNewRoute
  '/(admin)/finance/payments/$paymentId': typeof adminFinancePaymentsPaymentIdRoute
  '/(admin)/finance/payments/failed': typeof adminFinancePaymentsFailedRoute
  '/(admin)/finance/subscriptions/upcoming': typeof adminFinanceSubscriptionsUpcomingRoute
  '/(admin)/legal/pages/$pageSlug': typeof adminLegalPagesPageSlugRoute
  '/(admin)/operations/orders/$orderId': typeof adminOperationsOrdersOrderIdRoute
  '/(admin)/platform/users/$userId': typeof adminPlatformUsersUserIdRoute
  '/(admin)/platform/users/activity': typeof adminPlatformUsersActivityRoute
  '/(admin)/platform/users/analytics': typeof adminPlatformUsersAnalyticsRoute
  '/(admin)/platform/users/list': typeof adminPlatformUsersListRoute
  '/(admin)/catalog/brands/': typeof adminCatalogBrandsIndexRoute
  '/(admin)/catalog/categories/': typeof adminCatalogCategoriesIndexRoute
  '/(admin)/catalog/hubs/': typeof adminCatalogHubsIndexRoute
  '/(admin)/catalog/products/': typeof adminCatalogProductsIndexRoute
  '/(admin)/catalog/vendors/': typeof adminCatalogVendorsIndexRoute
  '/(admin)/customers/broadcasts/': typeof adminCustomersBroadcastsIndexRoute
  '/(admin)/finance/coupons/': typeof adminFinanceCouponsIndexRoute
  '/(admin)/finance/payments/': typeof adminFinancePaymentsIndexRoute
  '/(admin)/finance/subscriptions/': typeof adminFinanceSubscriptionsIndexRoute
  '/(admin)/legal/pages/': typeof adminLegalPagesIndexRoute
  '/(admin)/operations/orders/': typeof adminOperationsOrdersIndexRoute
  '/(admin)/catalog/brands/$brandId/edit': typeof adminCatalogBrandsBrandIdEditRoute
  '/(admin)/catalog/hubs/$hubId/edit': typeof adminCatalogHubsHubIdEditRoute
  '/(admin)/catalog/products/$productId/edit': typeof adminCatalogProductsProductIdEditRoute
  '/(admin)/catalog/vendors/$vendorId/edit': typeof adminCatalogVendorsVendorIdEditRoute
  '/(admin)/finance/coupons/$couponId/edit': typeof adminFinanceCouponsCouponIdEditRoute
  '/(admin)/catalog/brands/$brandId/': typeof adminCatalogBrandsBrandIdIndexRoute
  '/(admin)/catalog/hubs/$hubId/': typeof adminCatalogHubsHubIdIndexRoute
  '/(admin)/catalog/vendors/$vendorId/': typeof adminCatalogVendorsVendorIdIndexRoute
  '/(admin)/finance/coupons/$couponId/': typeof adminFinanceCouponsCouponIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/forbidden'
    | '/auth/login'
    | '/'
    | '/catalog/collections'
    | '/catalog/merchandising'
    | '/catalog/pricing'
    | '/customers/journeys'
    | '/customers/referrals'
    | '/customers/reviews'
    | '/customers/segments'
    | '/finance/campaigns'
    | '/finance/reconciliation'
    | '/finance/refunds'
    | '/finance/tax'
    | '/legal/banners'
    | '/legal/config'
    | '/operations/service-areas'
    | '/overview/analytics'
    | '/overview/bi'
    | '/overview/ops'
    | '/platform/experiments'
    | '/platform/flags'
    | '/platform/integrations'
    | '/platform/system'
    | '/settings/activity-logs'
    | '/settings/profile'
    | '/staff/audit-log'
    | '/roles/'
    | '/staff/'
    | '/catalog/brands/new'
    | '/catalog/categories/$slug'
    | '/catalog/categories/new'
    | '/catalog/hubs/map'
    | '/catalog/hubs/new'
    | '/catalog/products/new'
    | '/catalog/vendors/new'
    | '/customers/broadcasts/new'
    | '/finance/coupons/new'
    | '/finance/payments/$paymentId'
    | '/finance/payments/failed'
    | '/finance/subscriptions/upcoming'
    | '/legal/pages/$pageSlug'
    | '/operations/orders/$orderId'
    | '/platform/users/$userId'
    | '/platform/users/activity'
    | '/platform/users/analytics'
    | '/platform/users/list'
    | '/catalog/brands/'
    | '/catalog/categories/'
    | '/catalog/hubs/'
    | '/catalog/products/'
    | '/catalog/vendors/'
    | '/customers/broadcasts/'
    | '/finance/coupons/'
    | '/finance/payments/'
    | '/finance/subscriptions/'
    | '/legal/pages/'
    | '/operations/orders/'
    | '/catalog/brands/$brandId/edit'
    | '/catalog/hubs/$hubId/edit'
    | '/catalog/products/$productId/edit'
    | '/catalog/vendors/$vendorId/edit'
    | '/finance/coupons/$couponId/edit'
    | '/catalog/brands/$brandId/'
    | '/catalog/hubs/$hubId/'
    | '/catalog/vendors/$vendorId/'
    | '/finance/coupons/$couponId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forbidden'
    | '/auth/login'
    | '/'
    | '/catalog/collections'
    | '/catalog/merchandising'
    | '/catalog/pricing'
    | '/customers/journeys'
    | '/customers/referrals'
    | '/customers/reviews'
    | '/customers/segments'
    | '/finance/campaigns'
    | '/finance/reconciliation'
    | '/finance/refunds'
    | '/finance/tax'
    | '/legal/banners'
    | '/legal/config'
    | '/operations/service-areas'
    | '/overview/analytics'
    | '/overview/bi'
    | '/overview/ops'
    | '/platform/experiments'
    | '/platform/flags'
    | '/platform/integrations'
    | '/platform/system'
    | '/settings/activity-logs'
    | '/settings/profile'
    | '/staff/audit-log'
    | '/roles'
    | '/staff'
    | '/catalog/brands/new'
    | '/catalog/categories/$slug'
    | '/catalog/categories/new'
    | '/catalog/hubs/map'
    | '/catalog/hubs/new'
    | '/catalog/products/new'
    | '/catalog/vendors/new'
    | '/customers/broadcasts/new'
    | '/finance/coupons/new'
    | '/finance/payments/$paymentId'
    | '/finance/payments/failed'
    | '/finance/subscriptions/upcoming'
    | '/legal/pages/$pageSlug'
    | '/operations/orders/$orderId'
    | '/platform/users/$userId'
    | '/platform/users/activity'
    | '/platform/users/analytics'
    | '/platform/users/list'
    | '/catalog/brands'
    | '/catalog/categories'
    | '/catalog/hubs'
    | '/catalog/products'
    | '/catalog/vendors'
    | '/customers/broadcasts'
    | '/finance/coupons'
    | '/finance/payments'
    | '/finance/subscriptions'
    | '/legal/pages'
    | '/operations/orders'
    | '/catalog/brands/$brandId/edit'
    | '/catalog/hubs/$hubId/edit'
    | '/catalog/products/$productId/edit'
    | '/catalog/vendors/$vendorId/edit'
    | '/finance/coupons/$couponId/edit'
    | '/catalog/brands/$brandId'
    | '/catalog/hubs/$hubId'
    | '/catalog/vendors/$vendorId'
    | '/finance/coupons/$couponId'
  id:
    | '__root__'
    | '/(admin)'
    | '/forbidden'
    | '/auth/login'
    | '/(admin)/'
    | '/(admin)/catalog/collections'
    | '/(admin)/catalog/merchandising'
    | '/(admin)/catalog/pricing'
    | '/(admin)/customers/journeys'
    | '/(admin)/customers/referrals'
    | '/(admin)/customers/reviews'
    | '/(admin)/customers/segments'
    | '/(admin)/finance/campaigns'
    | '/(admin)/finance/reconciliation'
    | '/(admin)/finance/refunds'
    | '/(admin)/finance/tax'
    | '/(admin)/legal/banners'
    | '/(admin)/legal/config'
    | '/(admin)/operations/service-areas'
    | '/(admin)/overview/analytics'
    | '/(admin)/overview/bi'
    | '/(admin)/overview/ops'
    | '/(admin)/platform/experiments'
    | '/(admin)/platform/flags'
    | '/(admin)/platform/integrations'
    | '/(admin)/platform/system'
    | '/(admin)/settings/activity-logs'
    | '/(admin)/settings/profile'
    | '/(admin)/staff/audit-log'
    | '/(admin)/roles/'
    | '/(admin)/staff/'
    | '/(admin)/catalog/brands/new'
    | '/(admin)/catalog/categories/$slug'
    | '/(admin)/catalog/categories/new'
    | '/(admin)/catalog/hubs/map'
    | '/(admin)/catalog/hubs/new'
    | '/(admin)/catalog/products/new'
    | '/(admin)/catalog/vendors/new'
    | '/(admin)/customers/broadcasts/new'
    | '/(admin)/finance/coupons/new'
    | '/(admin)/finance/payments/$paymentId'
    | '/(admin)/finance/payments/failed'
    | '/(admin)/finance/subscriptions/upcoming'
    | '/(admin)/legal/pages/$pageSlug'
    | '/(admin)/operations/orders/$orderId'
    | '/(admin)/platform/users/$userId'
    | '/(admin)/platform/users/activity'
    | '/(admin)/platform/users/analytics'
    | '/(admin)/platform/users/list'
    | '/(admin)/catalog/brands/'
    | '/(admin)/catalog/categories/'
    | '/(admin)/catalog/hubs/'
    | '/(admin)/catalog/products/'
    | '/(admin)/catalog/vendors/'
    | '/(admin)/customers/broadcasts/'
    | '/(admin)/finance/coupons/'
    | '/(admin)/finance/payments/'
    | '/(admin)/finance/subscriptions/'
    | '/(admin)/legal/pages/'
    | '/(admin)/operations/orders/'
    | '/(admin)/catalog/brands/$brandId/edit'
    | '/(admin)/catalog/hubs/$hubId/edit'
    | '/(admin)/catalog/products/$productId/edit'
    | '/(admin)/catalog/vendors/$vendorId/edit'
    | '/(admin)/finance/coupons/$couponId/edit'
    | '/(admin)/catalog/brands/$brandId/'
    | '/(admin)/catalog/hubs/$hubId/'
    | '/(admin)/catalog/vendors/$vendorId/'
    | '/(admin)/finance/coupons/$couponId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  adminLayoutRoute: typeof adminLayoutRouteWithChildren
  ForbiddenRoute: typeof ForbiddenRoute
  AuthLoginRoute: typeof AuthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)': {
      id: '/(admin)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof adminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/': {
      id: '/(admin)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof adminIndexRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/staff/': {
      id: '/(admin)/staff/'
      path: '/staff'
      fullPath: '/staff/'
      preLoaderRoute: typeof adminStaffIndexRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/roles/': {
      id: '/(admin)/roles/'
      path: '/roles'
      fullPath: '/roles/'
      preLoaderRoute: typeof adminRolesIndexRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/staff/audit-log': {
      id: '/(admin)/staff/audit-log'
      path: '/staff/audit-log'
      fullPath: '/staff/audit-log'
      preLoaderRoute: typeof adminStaffAuditLogRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/settings/profile': {
      id: '/(admin)/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof adminSettingsProfileRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/settings/activity-logs': {
      id: '/(admin)/settings/activity-logs'
      path: '/settings/activity-logs'
      fullPath: '/settings/activity-logs'
      preLoaderRoute: typeof adminSettingsActivityLogsRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/platform/system': {
      id: '/(admin)/platform/system'
      path: '/platform/system'
      fullPath: '/platform/system'
      preLoaderRoute: typeof adminPlatformSystemRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/platform/integrations': {
      id: '/(admin)/platform/integrations'
      path: '/platform/integrations'
      fullPath: '/platform/integrations'
      preLoaderRoute: typeof adminPlatformIntegrationsRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/platform/flags': {
      id: '/(admin)/platform/flags'
      path: '/platform/flags'
      fullPath: '/platform/flags'
      preLoaderRoute: typeof adminPlatformFlagsRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/platform/experiments': {
      id: '/(admin)/platform/experiments'
      path: '/platform/experiments'
      fullPath: '/platform/experiments'
      preLoaderRoute: typeof adminPlatformExperimentsRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/overview/ops': {
      id: '/(admin)/overview/ops'
      path: '/overview/ops'
      fullPath: '/overview/ops'
      preLoaderRoute: typeof adminOverviewOpsRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/overview/bi': {
      id: '/(admin)/overview/bi'
      path: '/overview/bi'
      fullPath: '/overview/bi'
      preLoaderRoute: typeof adminOverviewBiRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/overview/analytics': {
      id: '/(admin)/overview/analytics'
      path: '/overview/analytics'
      fullPath: '/overview/analytics'
      preLoaderRoute: typeof adminOverviewAnalyticsRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/operations/service-areas': {
      id: '/(admin)/operations/service-areas'
      path: '/operations/service-areas'
      fullPath: '/operations/service-areas'
      preLoaderRoute: typeof adminOperationsServiceAreasRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/legal/config': {
      id: '/(admin)/legal/config'
      path: '/legal/config'
      fullPath: '/legal/config'
      preLoaderRoute: typeof adminLegalConfigRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/legal/banners': {
      id: '/(admin)/legal/banners'
      path: '/legal/banners'
      fullPath: '/legal/banners'
      preLoaderRoute: typeof adminLegalBannersRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/finance/tax': {
      id: '/(admin)/finance/tax'
      path: '/finance/tax'
      fullPath: '/finance/tax'
      preLoaderRoute: typeof adminFinanceTaxRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/finance/refunds': {
      id: '/(admin)/finance/refunds'
      path: '/finance/refunds'
      fullPath: '/finance/refunds'
      preLoaderRoute: typeof adminFinanceRefundsRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/finance/reconciliation': {
      id: '/(admin)/finance/reconciliation'
      path: '/finance/reconciliation'
      fullPath: '/finance/reconciliation'
      preLoaderRoute: typeof adminFinanceReconciliationRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/finance/campaigns': {
      id: '/(admin)/finance/campaigns'
      path: '/finance/campaigns'
      fullPath: '/finance/campaigns'
      preLoaderRoute: typeof adminFinanceCampaignsRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/customers/segments': {
      id: '/(admin)/customers/segments'
      path: '/customers/segments'
      fullPath: '/customers/segments'
      preLoaderRoute: typeof adminCustomersSegmentsRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/customers/reviews': {
      id: '/(admin)/customers/reviews'
      path: '/customers/reviews'
      fullPath: '/customers/reviews'
      preLoaderRoute: typeof adminCustomersReviewsRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/customers/referrals': {
      id: '/(admin)/customers/referrals'
      path: '/customers/referrals'
      fullPath: '/customers/referrals'
      preLoaderRoute: typeof adminCustomersReferralsRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/customers/journeys': {
      id: '/(admin)/customers/journeys'
      path: '/customers/journeys'
      fullPath: '/customers/journeys'
      preLoaderRoute: typeof adminCustomersJourneysRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/catalog/pricing': {
      id: '/(admin)/catalog/pricing'
      path: '/catalog/pricing'
      fullPath: '/catalog/pricing'
      preLoaderRoute: typeof adminCatalogPricingRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/catalog/merchandising': {
      id: '/(admin)/catalog/merchandising'
      path: '/catalog/merchandising'
      fullPath: '/catalog/merchandising'
      preLoaderRoute: typeof adminCatalogMerchandisingRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/catalog/collections': {
      id: '/(admin)/catalog/collections'
      path: '/catalog/collections'
      fullPath: '/catalog/collections'
      preLoaderRoute: typeof adminCatalogCollectionsRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/operations/orders/': {
      id: '/(admin)/operations/orders/'
      path: '/operations/orders'
      fullPath: '/operations/orders/'
      preLoaderRoute: typeof adminOperationsOrdersIndexRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/legal/pages/': {
      id: '/(admin)/legal/pages/'
      path: '/legal/pages'
      fullPath: '/legal/pages/'
      preLoaderRoute: typeof adminLegalPagesIndexRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/finance/subscriptions/': {
      id: '/(admin)/finance/subscriptions/'
      path: '/finance/subscriptions'
      fullPath: '/finance/subscriptions/'
      preLoaderRoute: typeof adminFinanceSubscriptionsIndexRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/finance/payments/': {
      id: '/(admin)/finance/payments/'
      path: '/finance/payments'
      fullPath: '/finance/payments/'
      preLoaderRoute: typeof adminFinancePaymentsIndexRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/finance/coupons/': {
      id: '/(admin)/finance/coupons/'
      path: '/finance/coupons'
      fullPath: '/finance/coupons/'
      preLoaderRoute: typeof adminFinanceCouponsIndexRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/customers/broadcasts/': {
      id: '/(admin)/customers/broadcasts/'
      path: '/customers/broadcasts'
      fullPath: '/customers/broadcasts/'
      preLoaderRoute: typeof adminCustomersBroadcastsIndexRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/catalog/vendors/': {
      id: '/(admin)/catalog/vendors/'
      path: '/catalog/vendors'
      fullPath: '/catalog/vendors/'
      preLoaderRoute: typeof adminCatalogVendorsIndexRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/catalog/products/': {
      id: '/(admin)/catalog/products/'
      path: '/catalog/products'
      fullPath: '/catalog/products/'
      preLoaderRoute: typeof adminCatalogProductsIndexRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/catalog/hubs/': {
      id: '/(admin)/catalog/hubs/'
      path: '/catalog/hubs'
      fullPath: '/catalog/hubs/'
      preLoaderRoute: typeof adminCatalogHubsIndexRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/catalog/categories/': {
      id: '/(admin)/catalog/categories/'
      path: '/catalog/categories'
      fullPath: '/catalog/categories/'
      preLoaderRoute: typeof adminCatalogCategoriesIndexRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/catalog/brands/': {
      id: '/(admin)/catalog/brands/'
      path: '/catalog/brands'
      fullPath: '/catalog/brands/'
      preLoaderRoute: typeof adminCatalogBrandsIndexRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/platform/users/list': {
      id: '/(admin)/platform/users/list'
      path: '/platform/users/list'
      fullPath: '/platform/users/list'
      preLoaderRoute: typeof adminPlatformUsersListRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/platform/users/analytics': {
      id: '/(admin)/platform/users/analytics'
      path: '/platform/users/analytics'
      fullPath: '/platform/users/analytics'
      preLoaderRoute: typeof adminPlatformUsersAnalyticsRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/platform/users/activity': {
      id: '/(admin)/platform/users/activity'
      path: '/platform/users/activity'
      fullPath: '/platform/users/activity'
      preLoaderRoute: typeof adminPlatformUsersActivityRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/platform/users/$userId': {
      id: '/(admin)/platform/users/$userId'
      path: '/platform/users/$userId'
      fullPath: '/platform/users/$userId'
      preLoaderRoute: typeof adminPlatformUsersUserIdRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/operations/orders/$orderId': {
      id: '/(admin)/operations/orders/$orderId'
      path: '/operations/orders/$orderId'
      fullPath: '/operations/orders/$orderId'
      preLoaderRoute: typeof adminOperationsOrdersOrderIdRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/legal/pages/$pageSlug': {
      id: '/(admin)/legal/pages/$pageSlug'
      path: '/legal/pages/$pageSlug'
      fullPath: '/legal/pages/$pageSlug'
      preLoaderRoute: typeof adminLegalPagesPageSlugRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/finance/subscriptions/upcoming': {
      id: '/(admin)/finance/subscriptions/upcoming'
      path: '/finance/subscriptions/upcoming'
      fullPath: '/finance/subscriptions/upcoming'
      preLoaderRoute: typeof adminFinanceSubscriptionsUpcomingRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/finance/payments/failed': {
      id: '/(admin)/finance/payments/failed'
      path: '/finance/payments/failed'
      fullPath: '/finance/payments/failed'
      preLoaderRoute: typeof adminFinancePaymentsFailedRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/finance/payments/$paymentId': {
      id: '/(admin)/finance/payments/$paymentId'
      path: '/finance/payments/$paymentId'
      fullPath: '/finance/payments/$paymentId'
      preLoaderRoute: typeof adminFinancePaymentsPaymentIdRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/finance/coupons/new': {
      id: '/(admin)/finance/coupons/new'
      path: '/finance/coupons/new'
      fullPath: '/finance/coupons/new'
      preLoaderRoute: typeof adminFinanceCouponsNewRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/customers/broadcasts/new': {
      id: '/(admin)/customers/broadcasts/new'
      path: '/customers/broadcasts/new'
      fullPath: '/customers/broadcasts/new'
      preLoaderRoute: typeof adminCustomersBroadcastsNewRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/catalog/vendors/new': {
      id: '/(admin)/catalog/vendors/new'
      path: '/catalog/vendors/new'
      fullPath: '/catalog/vendors/new'
      preLoaderRoute: typeof adminCatalogVendorsNewRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/catalog/products/new': {
      id: '/(admin)/catalog/products/new'
      path: '/catalog/products/new'
      fullPath: '/catalog/products/new'
      preLoaderRoute: typeof adminCatalogProductsNewRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/catalog/hubs/new': {
      id: '/(admin)/catalog/hubs/new'
      path: '/catalog/hubs/new'
      fullPath: '/catalog/hubs/new'
      preLoaderRoute: typeof adminCatalogHubsNewRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/catalog/hubs/map': {
      id: '/(admin)/catalog/hubs/map'
      path: '/catalog/hubs/map'
      fullPath: '/catalog/hubs/map'
      preLoaderRoute: typeof adminCatalogHubsMapRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/catalog/categories/new': {
      id: '/(admin)/catalog/categories/new'
      path: '/catalog/categories/new'
      fullPath: '/catalog/categories/new'
      preLoaderRoute: typeof adminCatalogCategoriesNewRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/catalog/categories/$slug': {
      id: '/(admin)/catalog/categories/$slug'
      path: '/catalog/categories/$slug'
      fullPath: '/catalog/categories/$slug'
      preLoaderRoute: typeof adminCatalogCategoriesSlugRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/catalog/brands/new': {
      id: '/(admin)/catalog/brands/new'
      path: '/catalog/brands/new'
      fullPath: '/catalog/brands/new'
      preLoaderRoute: typeof adminCatalogBrandsNewRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/finance/coupons/$couponId/': {
      id: '/(admin)/finance/coupons/$couponId/'
      path: '/finance/coupons/$couponId'
      fullPath: '/finance/coupons/$couponId/'
      preLoaderRoute: typeof adminFinanceCouponsCouponIdIndexRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/catalog/vendors/$vendorId/': {
      id: '/(admin)/catalog/vendors/$vendorId/'
      path: '/catalog/vendors/$vendorId'
      fullPath: '/catalog/vendors/$vendorId/'
      preLoaderRoute: typeof adminCatalogVendorsVendorIdIndexRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/catalog/hubs/$hubId/': {
      id: '/(admin)/catalog/hubs/$hubId/'
      path: '/catalog/hubs/$hubId'
      fullPath: '/catalog/hubs/$hubId/'
      preLoaderRoute: typeof adminCatalogHubsHubIdIndexRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/catalog/brands/$brandId/': {
      id: '/(admin)/catalog/brands/$brandId/'
      path: '/catalog/brands/$brandId'
      fullPath: '/catalog/brands/$brandId/'
      preLoaderRoute: typeof adminCatalogBrandsBrandIdIndexRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/finance/coupons/$couponId/edit': {
      id: '/(admin)/finance/coupons/$couponId/edit'
      path: '/finance/coupons/$couponId/edit'
      fullPath: '/finance/coupons/$couponId/edit'
      preLoaderRoute: typeof adminFinanceCouponsCouponIdEditRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/catalog/vendors/$vendorId/edit': {
      id: '/(admin)/catalog/vendors/$vendorId/edit'
      path: '/catalog/vendors/$vendorId/edit'
      fullPath: '/catalog/vendors/$vendorId/edit'
      preLoaderRoute: typeof adminCatalogVendorsVendorIdEditRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/catalog/products/$productId/edit': {
      id: '/(admin)/catalog/products/$productId/edit'
      path: '/catalog/products/$productId/edit'
      fullPath: '/catalog/products/$productId/edit'
      preLoaderRoute: typeof adminCatalogProductsProductIdEditRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/catalog/hubs/$hubId/edit': {
      id: '/(admin)/catalog/hubs/$hubId/edit'
      path: '/catalog/hubs/$hubId/edit'
      fullPath: '/catalog/hubs/$hubId/edit'
      preLoaderRoute: typeof adminCatalogHubsHubIdEditRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/catalog/brands/$brandId/edit': {
      id: '/(admin)/catalog/brands/$brandId/edit'
      path: '/catalog/brands/$brandId/edit'
      fullPath: '/catalog/brands/$brandId/edit'
      preLoaderRoute: typeof adminCatalogBrandsBrandIdEditRouteImport
      parentRoute: typeof adminLayoutRoute
    }
  }
}

interface adminLayoutRouteChildren {
  adminIndexRoute: typeof adminIndexRoute
  adminCatalogCollectionsRoute: typeof adminCatalogCollectionsRoute
  adminCatalogMerchandisingRoute: typeof adminCatalogMerchandisingRoute
  adminCatalogPricingRoute: typeof adminCatalogPricingRoute
  adminCustomersJourneysRoute: typeof adminCustomersJourneysRoute
  adminCustomersReferralsRoute: typeof adminCustomersReferralsRoute
  adminCustomersReviewsRoute: typeof adminCustomersReviewsRoute
  adminCustomersSegmentsRoute: typeof adminCustomersSegmentsRoute
  adminFinanceCampaignsRoute: typeof adminFinanceCampaignsRoute
  adminFinanceReconciliationRoute: typeof adminFinanceReconciliationRoute
  adminFinanceRefundsRoute: typeof adminFinanceRefundsRoute
  adminFinanceTaxRoute: typeof adminFinanceTaxRoute
  adminLegalBannersRoute: typeof adminLegalBannersRoute
  adminLegalConfigRoute: typeof adminLegalConfigRoute
  adminOperationsServiceAreasRoute: typeof adminOperationsServiceAreasRoute
  adminOverviewAnalyticsRoute: typeof adminOverviewAnalyticsRoute
  adminOverviewBiRoute: typeof adminOverviewBiRoute
  adminOverviewOpsRoute: typeof adminOverviewOpsRoute
  adminPlatformExperimentsRoute: typeof adminPlatformExperimentsRoute
  adminPlatformFlagsRoute: typeof adminPlatformFlagsRoute
  adminPlatformIntegrationsRoute: typeof adminPlatformIntegrationsRoute
  adminPlatformSystemRoute: typeof adminPlatformSystemRoute
  adminSettingsActivityLogsRoute: typeof adminSettingsActivityLogsRoute
  adminSettingsProfileRoute: typeof adminSettingsProfileRoute
  adminStaffAuditLogRoute: typeof adminStaffAuditLogRoute
  adminRolesIndexRoute: typeof adminRolesIndexRoute
  adminStaffIndexRoute: typeof adminStaffIndexRoute
  adminCatalogBrandsNewRoute: typeof adminCatalogBrandsNewRoute
  adminCatalogCategoriesSlugRoute: typeof adminCatalogCategoriesSlugRoute
  adminCatalogCategoriesNewRoute: typeof adminCatalogCategoriesNewRoute
  adminCatalogHubsMapRoute: typeof adminCatalogHubsMapRoute
  adminCatalogHubsNewRoute: typeof adminCatalogHubsNewRoute
  adminCatalogProductsNewRoute: typeof adminCatalogProductsNewRoute
  adminCatalogVendorsNewRoute: typeof adminCatalogVendorsNewRoute
  adminCustomersBroadcastsNewRoute: typeof adminCustomersBroadcastsNewRoute
  adminFinanceCouponsNewRoute: typeof adminFinanceCouponsNewRoute
  adminFinancePaymentsPaymentIdRoute: typeof adminFinancePaymentsPaymentIdRoute
  adminFinancePaymentsFailedRoute: typeof adminFinancePaymentsFailedRoute
  adminFinanceSubscriptionsUpcomingRoute: typeof adminFinanceSubscriptionsUpcomingRoute
  adminLegalPagesPageSlugRoute: typeof adminLegalPagesPageSlugRoute
  adminOperationsOrdersOrderIdRoute: typeof adminOperationsOrdersOrderIdRoute
  adminPlatformUsersUserIdRoute: typeof adminPlatformUsersUserIdRoute
  adminPlatformUsersActivityRoute: typeof adminPlatformUsersActivityRoute
  adminPlatformUsersAnalyticsRoute: typeof adminPlatformUsersAnalyticsRoute
  adminPlatformUsersListRoute: typeof adminPlatformUsersListRoute
  adminCatalogBrandsIndexRoute: typeof adminCatalogBrandsIndexRoute
  adminCatalogCategoriesIndexRoute: typeof adminCatalogCategoriesIndexRoute
  adminCatalogHubsIndexRoute: typeof adminCatalogHubsIndexRoute
  adminCatalogProductsIndexRoute: typeof adminCatalogProductsIndexRoute
  adminCatalogVendorsIndexRoute: typeof adminCatalogVendorsIndexRoute
  adminCustomersBroadcastsIndexRoute: typeof adminCustomersBroadcastsIndexRoute
  adminFinanceCouponsIndexRoute: typeof adminFinanceCouponsIndexRoute
  adminFinancePaymentsIndexRoute: typeof adminFinancePaymentsIndexRoute
  adminFinanceSubscriptionsIndexRoute: typeof adminFinanceSubscriptionsIndexRoute
  adminLegalPagesIndexRoute: typeof adminLegalPagesIndexRoute
  adminOperationsOrdersIndexRoute: typeof adminOperationsOrdersIndexRoute
  adminCatalogBrandsBrandIdEditRoute: typeof adminCatalogBrandsBrandIdEditRoute
  adminCatalogHubsHubIdEditRoute: typeof adminCatalogHubsHubIdEditRoute
  adminCatalogProductsProductIdEditRoute: typeof adminCatalogProductsProductIdEditRoute
  adminCatalogVendorsVendorIdEditRoute: typeof adminCatalogVendorsVendorIdEditRoute
  adminFinanceCouponsCouponIdEditRoute: typeof adminFinanceCouponsCouponIdEditRoute
  adminCatalogBrandsBrandIdIndexRoute: typeof adminCatalogBrandsBrandIdIndexRoute
  adminCatalogHubsHubIdIndexRoute: typeof adminCatalogHubsHubIdIndexRoute
  adminCatalogVendorsVendorIdIndexRoute: typeof adminCatalogVendorsVendorIdIndexRoute
  adminFinanceCouponsCouponIdIndexRoute: typeof adminFinanceCouponsCouponIdIndexRoute
}

const adminLayoutRouteChildren: adminLayoutRouteChildren = {
  adminIndexRoute: adminIndexRoute,
  adminCatalogCollectionsRoute: adminCatalogCollectionsRoute,
  adminCatalogMerchandisingRoute: adminCatalogMerchandisingRoute,
  adminCatalogPricingRoute: adminCatalogPricingRoute,
  adminCustomersJourneysRoute: adminCustomersJourneysRoute,
  adminCustomersReferralsRoute: adminCustomersReferralsRoute,
  adminCustomersReviewsRoute: adminCustomersReviewsRoute,
  adminCustomersSegmentsRoute: adminCustomersSegmentsRoute,
  adminFinanceCampaignsRoute: adminFinanceCampaignsRoute,
  adminFinanceReconciliationRoute: adminFinanceReconciliationRoute,
  adminFinanceRefundsRoute: adminFinanceRefundsRoute,
  adminFinanceTaxRoute: adminFinanceTaxRoute,
  adminLegalBannersRoute: adminLegalBannersRoute,
  adminLegalConfigRoute: adminLegalConfigRoute,
  adminOperationsServiceAreasRoute: adminOperationsServiceAreasRoute,
  adminOverviewAnalyticsRoute: adminOverviewAnalyticsRoute,
  adminOverviewBiRoute: adminOverviewBiRoute,
  adminOverviewOpsRoute: adminOverviewOpsRoute,
  adminPlatformExperimentsRoute: adminPlatformExperimentsRoute,
  adminPlatformFlagsRoute: adminPlatformFlagsRoute,
  adminPlatformIntegrationsRoute: adminPlatformIntegrationsRoute,
  adminPlatformSystemRoute: adminPlatformSystemRoute,
  adminSettingsActivityLogsRoute: adminSettingsActivityLogsRoute,
  adminSettingsProfileRoute: adminSettingsProfileRoute,
  adminStaffAuditLogRoute: adminStaffAuditLogRoute,
  adminRolesIndexRoute: adminRolesIndexRoute,
  adminStaffIndexRoute: adminStaffIndexRoute,
  adminCatalogBrandsNewRoute: adminCatalogBrandsNewRoute,
  adminCatalogCategoriesSlugRoute: adminCatalogCategoriesSlugRoute,
  adminCatalogCategoriesNewRoute: adminCatalogCategoriesNewRoute,
  adminCatalogHubsMapRoute: adminCatalogHubsMapRoute,
  adminCatalogHubsNewRoute: adminCatalogHubsNewRoute,
  adminCatalogProductsNewRoute: adminCatalogProductsNewRoute,
  adminCatalogVendorsNewRoute: adminCatalogVendorsNewRoute,
  adminCustomersBroadcastsNewRoute: adminCustomersBroadcastsNewRoute,
  adminFinanceCouponsNewRoute: adminFinanceCouponsNewRoute,
  adminFinancePaymentsPaymentIdRoute: adminFinancePaymentsPaymentIdRoute,
  adminFinancePaymentsFailedRoute: adminFinancePaymentsFailedRoute,
  adminFinanceSubscriptionsUpcomingRoute:
    adminFinanceSubscriptionsUpcomingRoute,
  adminLegalPagesPageSlugRoute: adminLegalPagesPageSlugRoute,
  adminOperationsOrdersOrderIdRoute: adminOperationsOrdersOrderIdRoute,
  adminPlatformUsersUserIdRoute: adminPlatformUsersUserIdRoute,
  adminPlatformUsersActivityRoute: adminPlatformUsersActivityRoute,
  adminPlatformUsersAnalyticsRoute: adminPlatformUsersAnalyticsRoute,
  adminPlatformUsersListRoute: adminPlatformUsersListRoute,
  adminCatalogBrandsIndexRoute: adminCatalogBrandsIndexRoute,
  adminCatalogCategoriesIndexRoute: adminCatalogCategoriesIndexRoute,
  adminCatalogHubsIndexRoute: adminCatalogHubsIndexRoute,
  adminCatalogProductsIndexRoute: adminCatalogProductsIndexRoute,
  adminCatalogVendorsIndexRoute: adminCatalogVendorsIndexRoute,
  adminCustomersBroadcastsIndexRoute: adminCustomersBroadcastsIndexRoute,
  adminFinanceCouponsIndexRoute: adminFinanceCouponsIndexRoute,
  adminFinancePaymentsIndexRoute: adminFinancePaymentsIndexRoute,
  adminFinanceSubscriptionsIndexRoute: adminFinanceSubscriptionsIndexRoute,
  adminLegalPagesIndexRoute: adminLegalPagesIndexRoute,
  adminOperationsOrdersIndexRoute: adminOperationsOrdersIndexRoute,
  adminCatalogBrandsBrandIdEditRoute: adminCatalogBrandsBrandIdEditRoute,
  adminCatalogHubsHubIdEditRoute: adminCatalogHubsHubIdEditRoute,
  adminCatalogProductsProductIdEditRoute:
    adminCatalogProductsProductIdEditRoute,
  adminCatalogVendorsVendorIdEditRoute: adminCatalogVendorsVendorIdEditRoute,
  adminFinanceCouponsCouponIdEditRoute: adminFinanceCouponsCouponIdEditRoute,
  adminCatalogBrandsBrandIdIndexRoute: adminCatalogBrandsBrandIdIndexRoute,
  adminCatalogHubsHubIdIndexRoute: adminCatalogHubsHubIdIndexRoute,
  adminCatalogVendorsVendorIdIndexRoute: adminCatalogVendorsVendorIdIndexRoute,
  adminFinanceCouponsCouponIdIndexRoute: adminFinanceCouponsCouponIdIndexRoute,
}

const adminLayoutRouteWithChildren = adminLayoutRoute._addFileChildren(
  adminLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  adminLayoutRoute: adminLayoutRouteWithChildren,
  ForbiddenRoute: ForbiddenRoute,
  AuthLoginRoute: AuthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
