/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as AuthLayoutRouteImport } from './pages/auth/_layout'
import { Route as storeLayoutRouteImport } from './pages/(store)/_layout'
import { Route as storeIndexRouteImport } from './pages/(store)/index'
import { Route as AuthRegisterRouteImport } from './pages/auth/register'
import { Route as AuthOtpRouteImport } from './pages/auth/otp'
import { Route as AuthLoginRouteImport } from './pages/auth/login'
import { Route as storeSearchRouteImport } from './pages/(store)/search'
import { Route as storeHelpRouteImport } from './pages/(store)/help'
import { Route as storeContactRouteImport } from './pages/(store)/contact'
import { Route as storeCartRouteImport } from './pages/(store)/cart'
import { Route as storeAboutRouteImport } from './pages/(store)/about'
import { Route as storeprotectedLayoutRouteImport } from './pages/(store)/(protected)/_layout'
import { Route as storeProfileIndexRouteImport } from './pages/(store)/profile/index'
import { Route as storeProductIndexRouteImport } from './pages/(store)/product/index'
import { Route as storeProfileBabyRouteImport } from './pages/(store)/profile/baby'
import { Route as storeLegalTermsRouteImport } from './pages/(store)/legal/terms'
import { Route as storeLegalShippingRouteImport } from './pages/(store)/legal/shipping'
import { Route as storeLegalReturnsRouteImport } from './pages/(store)/legal/returns'
import { Route as storeLegalPrivacyRouteImport } from './pages/(store)/legal/privacy'
import { Route as storeprotectedWishlistRouteImport } from './pages/(store)/(protected)/wishlist'
import { Route as storeprotectedNotificationsRouteImport } from './pages/(store)/(protected)/notifications'
import { Route as storeprotectedAddressesRouteImport } from './pages/(store)/(protected)/addresses'
import { Route as storeprotectedCheckoutLayoutRouteImport } from './pages/(store)/(protected)/checkout/_layout'
import { Route as storeProductProductIdIndexRouteImport } from './pages/(store)/product/$productId/index'
import { Route as storeprotectedOrdersIndexRouteImport } from './pages/(store)/(protected)/orders/index'
import { Route as storeprotectedCheckoutIndexRouteImport } from './pages/(store)/(protected)/checkout/index'
import { Route as storeProductProductIdReviewsRouteImport } from './pages/(store)/product/$productId/reviews'
import { Route as storeprotectedPaymentStatusRouteImport } from './pages/(store)/(protected)/payment/status'
import { Route as storeprotectedCheckoutReviewRouteImport } from './pages/(store)/(protected)/checkout/review'
import { Route as storeprotectedCheckoutPaymentRouteImport } from './pages/(store)/(protected)/checkout/payment'
import { Route as storeprotectedCheckoutAddressRouteImport } from './pages/(store)/(protected)/checkout/address'
import { Route as storeprotectedOrdersOrderIdIndexRouteImport } from './pages/(store)/(protected)/orders/$orderId/index'
import { Route as storeprotectedOrdersOrderIdTrackingRouteImport } from './pages/(store)/(protected)/orders/$orderId/tracking'
import { Route as storeprotectedOrdersOrderIdReturnRouteImport } from './pages/(store)/(protected)/orders/$orderId/return'

const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const storeLayoutRoute = storeLayoutRouteImport.update({
  id: '/(store)',
  getParentRoute: () => rootRouteImport,
} as any)
const storeIndexRoute = storeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => storeLayoutRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthOtpRoute = AuthOtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const storeSearchRoute = storeSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => storeLayoutRoute,
} as any)
const storeHelpRoute = storeHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => storeLayoutRoute,
} as any)
const storeContactRoute = storeContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => storeLayoutRoute,
} as any)
const storeCartRoute = storeCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => storeLayoutRoute,
} as any)
const storeAboutRoute = storeAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => storeLayoutRoute,
} as any)
const storeprotectedLayoutRoute = storeprotectedLayoutRouteImport.update({
  id: '/(protected)',
  getParentRoute: () => storeLayoutRoute,
} as any)
const storeProfileIndexRoute = storeProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => storeLayoutRoute,
} as any)
const storeProductIndexRoute = storeProductIndexRouteImport.update({
  id: '/product/',
  path: '/product/',
  getParentRoute: () => storeLayoutRoute,
} as any)
const storeProfileBabyRoute = storeProfileBabyRouteImport.update({
  id: '/profile/baby',
  path: '/profile/baby',
  getParentRoute: () => storeLayoutRoute,
} as any)
const storeLegalTermsRoute = storeLegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => storeLayoutRoute,
} as any)
const storeLegalShippingRoute = storeLegalShippingRouteImport.update({
  id: '/legal/shipping',
  path: '/legal/shipping',
  getParentRoute: () => storeLayoutRoute,
} as any)
const storeLegalReturnsRoute = storeLegalReturnsRouteImport.update({
  id: '/legal/returns',
  path: '/legal/returns',
  getParentRoute: () => storeLayoutRoute,
} as any)
const storeLegalPrivacyRoute = storeLegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => storeLayoutRoute,
} as any)
const storeprotectedWishlistRoute = storeprotectedWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => storeprotectedLayoutRoute,
} as any)
const storeprotectedNotificationsRoute =
  storeprotectedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => storeprotectedLayoutRoute,
  } as any)
const storeprotectedAddressesRoute = storeprotectedAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => storeprotectedLayoutRoute,
} as any)
const storeprotectedCheckoutLayoutRoute =
  storeprotectedCheckoutLayoutRouteImport.update({
    id: '/checkout',
    path: '/checkout',
    getParentRoute: () => storeprotectedLayoutRoute,
  } as any)
const storeProductProductIdIndexRoute =
  storeProductProductIdIndexRouteImport.update({
    id: '/product/$productId/',
    path: '/product/$productId/',
    getParentRoute: () => storeLayoutRoute,
  } as any)
const storeprotectedOrdersIndexRoute =
  storeprotectedOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => storeprotectedLayoutRoute,
  } as any)
const storeprotectedCheckoutIndexRoute =
  storeprotectedCheckoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => storeprotectedCheckoutLayoutRoute,
  } as any)
const storeProductProductIdReviewsRoute =
  storeProductProductIdReviewsRouteImport.update({
    id: '/product/$productId/reviews',
    path: '/product/$productId/reviews',
    getParentRoute: () => storeLayoutRoute,
  } as any)
const storeprotectedPaymentStatusRoute =
  storeprotectedPaymentStatusRouteImport.update({
    id: '/payment/status',
    path: '/payment/status',
    getParentRoute: () => storeprotectedLayoutRoute,
  } as any)
const storeprotectedCheckoutReviewRoute =
  storeprotectedCheckoutReviewRouteImport.update({
    id: '/review',
    path: '/review',
    getParentRoute: () => storeprotectedCheckoutLayoutRoute,
  } as any)
const storeprotectedCheckoutPaymentRoute =
  storeprotectedCheckoutPaymentRouteImport.update({
    id: '/payment',
    path: '/payment',
    getParentRoute: () => storeprotectedCheckoutLayoutRoute,
  } as any)
const storeprotectedCheckoutAddressRoute =
  storeprotectedCheckoutAddressRouteImport.update({
    id: '/address',
    path: '/address',
    getParentRoute: () => storeprotectedCheckoutLayoutRoute,
  } as any)
const storeprotectedOrdersOrderIdIndexRoute =
  storeprotectedOrdersOrderIdIndexRouteImport.update({
    id: '/orders/$orderId/',
    path: '/orders/$orderId/',
    getParentRoute: () => storeprotectedLayoutRoute,
  } as any)
const storeprotectedOrdersOrderIdTrackingRoute =
  storeprotectedOrdersOrderIdTrackingRouteImport.update({
    id: '/orders/$orderId/tracking',
    path: '/orders/$orderId/tracking',
    getParentRoute: () => storeprotectedLayoutRoute,
  } as any)
const storeprotectedOrdersOrderIdReturnRoute =
  storeprotectedOrdersOrderIdReturnRouteImport.update({
    id: '/orders/$orderId/return',
    path: '/orders/$orderId/return',
    getParentRoute: () => storeprotectedLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthLayoutRouteWithChildren
  '/about': typeof storeAboutRoute
  '/cart': typeof storeCartRoute
  '/contact': typeof storeContactRoute
  '/help': typeof storeHelpRoute
  '/search': typeof storeSearchRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/register': typeof AuthRegisterRoute
  '/': typeof storeIndexRoute
  '/checkout': typeof storeprotectedCheckoutLayoutRouteWithChildren
  '/addresses': typeof storeprotectedAddressesRoute
  '/notifications': typeof storeprotectedNotificationsRoute
  '/wishlist': typeof storeprotectedWishlistRoute
  '/legal/privacy': typeof storeLegalPrivacyRoute
  '/legal/returns': typeof storeLegalReturnsRoute
  '/legal/shipping': typeof storeLegalShippingRoute
  '/legal/terms': typeof storeLegalTermsRoute
  '/profile/baby': typeof storeProfileBabyRoute
  '/product/': typeof storeProductIndexRoute
  '/profile/': typeof storeProfileIndexRoute
  '/checkout/address': typeof storeprotectedCheckoutAddressRoute
  '/checkout/payment': typeof storeprotectedCheckoutPaymentRoute
  '/checkout/review': typeof storeprotectedCheckoutReviewRoute
  '/payment/status': typeof storeprotectedPaymentStatusRoute
  '/product/$productId/reviews': typeof storeProductProductIdReviewsRoute
  '/checkout/': typeof storeprotectedCheckoutIndexRoute
  '/orders/': typeof storeprotectedOrdersIndexRoute
  '/product/$productId/': typeof storeProductProductIdIndexRoute
  '/orders/$orderId/return': typeof storeprotectedOrdersOrderIdReturnRoute
  '/orders/$orderId/tracking': typeof storeprotectedOrdersOrderIdTrackingRoute
  '/orders/$orderId/': typeof storeprotectedOrdersOrderIdIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthLayoutRouteWithChildren
  '/about': typeof storeAboutRoute
  '/cart': typeof storeCartRoute
  '/contact': typeof storeContactRoute
  '/help': typeof storeHelpRoute
  '/search': typeof storeSearchRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/register': typeof AuthRegisterRoute
  '/': typeof storeIndexRoute
  '/addresses': typeof storeprotectedAddressesRoute
  '/notifications': typeof storeprotectedNotificationsRoute
  '/wishlist': typeof storeprotectedWishlistRoute
  '/legal/privacy': typeof storeLegalPrivacyRoute
  '/legal/returns': typeof storeLegalReturnsRoute
  '/legal/shipping': typeof storeLegalShippingRoute
  '/legal/terms': typeof storeLegalTermsRoute
  '/profile/baby': typeof storeProfileBabyRoute
  '/product': typeof storeProductIndexRoute
  '/profile': typeof storeProfileIndexRoute
  '/checkout/address': typeof storeprotectedCheckoutAddressRoute
  '/checkout/payment': typeof storeprotectedCheckoutPaymentRoute
  '/checkout/review': typeof storeprotectedCheckoutReviewRoute
  '/payment/status': typeof storeprotectedPaymentStatusRoute
  '/product/$productId/reviews': typeof storeProductProductIdReviewsRoute
  '/checkout': typeof storeprotectedCheckoutIndexRoute
  '/orders': typeof storeprotectedOrdersIndexRoute
  '/product/$productId': typeof storeProductProductIdIndexRoute
  '/orders/$orderId/return': typeof storeprotectedOrdersOrderIdReturnRoute
  '/orders/$orderId/tracking': typeof storeprotectedOrdersOrderIdTrackingRoute
  '/orders/$orderId': typeof storeprotectedOrdersOrderIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(store)': typeof storeLayoutRouteWithChildren
  '/auth': typeof AuthLayoutRouteWithChildren
  '/(store)/(protected)': typeof storeprotectedLayoutRouteWithChildren
  '/(store)/about': typeof storeAboutRoute
  '/(store)/cart': typeof storeCartRoute
  '/(store)/contact': typeof storeContactRoute
  '/(store)/help': typeof storeHelpRoute
  '/(store)/search': typeof storeSearchRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/register': typeof AuthRegisterRoute
  '/(store)/': typeof storeIndexRoute
  '/(store)/(protected)/checkout': typeof storeprotectedCheckoutLayoutRouteWithChildren
  '/(store)/(protected)/addresses': typeof storeprotectedAddressesRoute
  '/(store)/(protected)/notifications': typeof storeprotectedNotificationsRoute
  '/(store)/(protected)/wishlist': typeof storeprotectedWishlistRoute
  '/(store)/legal/privacy': typeof storeLegalPrivacyRoute
  '/(store)/legal/returns': typeof storeLegalReturnsRoute
  '/(store)/legal/shipping': typeof storeLegalShippingRoute
  '/(store)/legal/terms': typeof storeLegalTermsRoute
  '/(store)/profile/baby': typeof storeProfileBabyRoute
  '/(store)/product/': typeof storeProductIndexRoute
  '/(store)/profile/': typeof storeProfileIndexRoute
  '/(store)/(protected)/checkout/address': typeof storeprotectedCheckoutAddressRoute
  '/(store)/(protected)/checkout/payment': typeof storeprotectedCheckoutPaymentRoute
  '/(store)/(protected)/checkout/review': typeof storeprotectedCheckoutReviewRoute
  '/(store)/(protected)/payment/status': typeof storeprotectedPaymentStatusRoute
  '/(store)/product/$productId/reviews': typeof storeProductProductIdReviewsRoute
  '/(store)/(protected)/checkout/': typeof storeprotectedCheckoutIndexRoute
  '/(store)/(protected)/orders/': typeof storeprotectedOrdersIndexRoute
  '/(store)/product/$productId/': typeof storeProductProductIdIndexRoute
  '/(store)/(protected)/orders/$orderId/return': typeof storeprotectedOrdersOrderIdReturnRoute
  '/(store)/(protected)/orders/$orderId/tracking': typeof storeprotectedOrdersOrderIdTrackingRoute
  '/(store)/(protected)/orders/$orderId/': typeof storeprotectedOrdersOrderIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/about'
    | '/cart'
    | '/contact'
    | '/help'
    | '/search'
    | '/auth/login'
    | '/auth/otp'
    | '/auth/register'
    | '/'
    | '/checkout'
    | '/addresses'
    | '/notifications'
    | '/wishlist'
    | '/legal/privacy'
    | '/legal/returns'
    | '/legal/shipping'
    | '/legal/terms'
    | '/profile/baby'
    | '/product/'
    | '/profile/'
    | '/checkout/address'
    | '/checkout/payment'
    | '/checkout/review'
    | '/payment/status'
    | '/product/$productId/reviews'
    | '/checkout/'
    | '/orders/'
    | '/product/$productId/'
    | '/orders/$orderId/return'
    | '/orders/$orderId/tracking'
    | '/orders/$orderId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/about'
    | '/cart'
    | '/contact'
    | '/help'
    | '/search'
    | '/auth/login'
    | '/auth/otp'
    | '/auth/register'
    | '/'
    | '/addresses'
    | '/notifications'
    | '/wishlist'
    | '/legal/privacy'
    | '/legal/returns'
    | '/legal/shipping'
    | '/legal/terms'
    | '/profile/baby'
    | '/product'
    | '/profile'
    | '/checkout/address'
    | '/checkout/payment'
    | '/checkout/review'
    | '/payment/status'
    | '/product/$productId/reviews'
    | '/checkout'
    | '/orders'
    | '/product/$productId'
    | '/orders/$orderId/return'
    | '/orders/$orderId/tracking'
    | '/orders/$orderId'
  id:
    | '__root__'
    | '/(store)'
    | '/auth'
    | '/(store)/(protected)'
    | '/(store)/about'
    | '/(store)/cart'
    | '/(store)/contact'
    | '/(store)/help'
    | '/(store)/search'
    | '/auth/login'
    | '/auth/otp'
    | '/auth/register'
    | '/(store)/'
    | '/(store)/(protected)/checkout'
    | '/(store)/(protected)/addresses'
    | '/(store)/(protected)/notifications'
    | '/(store)/(protected)/wishlist'
    | '/(store)/legal/privacy'
    | '/(store)/legal/returns'
    | '/(store)/legal/shipping'
    | '/(store)/legal/terms'
    | '/(store)/profile/baby'
    | '/(store)/product/'
    | '/(store)/profile/'
    | '/(store)/(protected)/checkout/address'
    | '/(store)/(protected)/checkout/payment'
    | '/(store)/(protected)/checkout/review'
    | '/(store)/(protected)/payment/status'
    | '/(store)/product/$productId/reviews'
    | '/(store)/(protected)/checkout/'
    | '/(store)/(protected)/orders/'
    | '/(store)/product/$productId/'
    | '/(store)/(protected)/orders/$orderId/return'
    | '/(store)/(protected)/orders/$orderId/tracking'
    | '/(store)/(protected)/orders/$orderId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  storeLayoutRoute: typeof storeLayoutRouteWithChildren
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(store)': {
      id: '/(store)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof storeLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(store)/': {
      id: '/(store)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof storeIndexRouteImport
      parentRoute: typeof storeLayoutRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/auth/otp': {
      id: '/auth/otp'
      path: '/otp'
      fullPath: '/auth/otp'
      preLoaderRoute: typeof AuthOtpRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/(store)/search': {
      id: '/(store)/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof storeSearchRouteImport
      parentRoute: typeof storeLayoutRoute
    }
    '/(store)/help': {
      id: '/(store)/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof storeHelpRouteImport
      parentRoute: typeof storeLayoutRoute
    }
    '/(store)/contact': {
      id: '/(store)/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof storeContactRouteImport
      parentRoute: typeof storeLayoutRoute
    }
    '/(store)/cart': {
      id: '/(store)/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof storeCartRouteImport
      parentRoute: typeof storeLayoutRoute
    }
    '/(store)/about': {
      id: '/(store)/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof storeAboutRouteImport
      parentRoute: typeof storeLayoutRoute
    }
    '/(store)/(protected)': {
      id: '/(store)/(protected)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof storeprotectedLayoutRouteImport
      parentRoute: typeof storeLayoutRoute
    }
    '/(store)/profile/': {
      id: '/(store)/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof storeProfileIndexRouteImport
      parentRoute: typeof storeLayoutRoute
    }
    '/(store)/product/': {
      id: '/(store)/product/'
      path: '/product'
      fullPath: '/product/'
      preLoaderRoute: typeof storeProductIndexRouteImport
      parentRoute: typeof storeLayoutRoute
    }
    '/(store)/profile/baby': {
      id: '/(store)/profile/baby'
      path: '/profile/baby'
      fullPath: '/profile/baby'
      preLoaderRoute: typeof storeProfileBabyRouteImport
      parentRoute: typeof storeLayoutRoute
    }
    '/(store)/legal/terms': {
      id: '/(store)/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof storeLegalTermsRouteImport
      parentRoute: typeof storeLayoutRoute
    }
    '/(store)/legal/shipping': {
      id: '/(store)/legal/shipping'
      path: '/legal/shipping'
      fullPath: '/legal/shipping'
      preLoaderRoute: typeof storeLegalShippingRouteImport
      parentRoute: typeof storeLayoutRoute
    }
    '/(store)/legal/returns': {
      id: '/(store)/legal/returns'
      path: '/legal/returns'
      fullPath: '/legal/returns'
      preLoaderRoute: typeof storeLegalReturnsRouteImport
      parentRoute: typeof storeLayoutRoute
    }
    '/(store)/legal/privacy': {
      id: '/(store)/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof storeLegalPrivacyRouteImport
      parentRoute: typeof storeLayoutRoute
    }
    '/(store)/(protected)/wishlist': {
      id: '/(store)/(protected)/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof storeprotectedWishlistRouteImport
      parentRoute: typeof storeprotectedLayoutRoute
    }
    '/(store)/(protected)/notifications': {
      id: '/(store)/(protected)/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof storeprotectedNotificationsRouteImport
      parentRoute: typeof storeprotectedLayoutRoute
    }
    '/(store)/(protected)/addresses': {
      id: '/(store)/(protected)/addresses'
      path: '/addresses'
      fullPath: '/addresses'
      preLoaderRoute: typeof storeprotectedAddressesRouteImport
      parentRoute: typeof storeprotectedLayoutRoute
    }
    '/(store)/(protected)/checkout': {
      id: '/(store)/(protected)/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof storeprotectedCheckoutLayoutRouteImport
      parentRoute: typeof storeprotectedLayoutRoute
    }
    '/(store)/product/$productId/': {
      id: '/(store)/product/$productId/'
      path: '/product/$productId'
      fullPath: '/product/$productId/'
      preLoaderRoute: typeof storeProductProductIdIndexRouteImport
      parentRoute: typeof storeLayoutRoute
    }
    '/(store)/(protected)/orders/': {
      id: '/(store)/(protected)/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof storeprotectedOrdersIndexRouteImport
      parentRoute: typeof storeprotectedLayoutRoute
    }
    '/(store)/(protected)/checkout/': {
      id: '/(store)/(protected)/checkout/'
      path: '/'
      fullPath: '/checkout/'
      preLoaderRoute: typeof storeprotectedCheckoutIndexRouteImport
      parentRoute: typeof storeprotectedCheckoutLayoutRoute
    }
    '/(store)/product/$productId/reviews': {
      id: '/(store)/product/$productId/reviews'
      path: '/product/$productId/reviews'
      fullPath: '/product/$productId/reviews'
      preLoaderRoute: typeof storeProductProductIdReviewsRouteImport
      parentRoute: typeof storeLayoutRoute
    }
    '/(store)/(protected)/payment/status': {
      id: '/(store)/(protected)/payment/status'
      path: '/payment/status'
      fullPath: '/payment/status'
      preLoaderRoute: typeof storeprotectedPaymentStatusRouteImport
      parentRoute: typeof storeprotectedLayoutRoute
    }
    '/(store)/(protected)/checkout/review': {
      id: '/(store)/(protected)/checkout/review'
      path: '/review'
      fullPath: '/checkout/review'
      preLoaderRoute: typeof storeprotectedCheckoutReviewRouteImport
      parentRoute: typeof storeprotectedCheckoutLayoutRoute
    }
    '/(store)/(protected)/checkout/payment': {
      id: '/(store)/(protected)/checkout/payment'
      path: '/payment'
      fullPath: '/checkout/payment'
      preLoaderRoute: typeof storeprotectedCheckoutPaymentRouteImport
      parentRoute: typeof storeprotectedCheckoutLayoutRoute
    }
    '/(store)/(protected)/checkout/address': {
      id: '/(store)/(protected)/checkout/address'
      path: '/address'
      fullPath: '/checkout/address'
      preLoaderRoute: typeof storeprotectedCheckoutAddressRouteImport
      parentRoute: typeof storeprotectedCheckoutLayoutRoute
    }
    '/(store)/(protected)/orders/$orderId/': {
      id: '/(store)/(protected)/orders/$orderId/'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId/'
      preLoaderRoute: typeof storeprotectedOrdersOrderIdIndexRouteImport
      parentRoute: typeof storeprotectedLayoutRoute
    }
    '/(store)/(protected)/orders/$orderId/tracking': {
      id: '/(store)/(protected)/orders/$orderId/tracking'
      path: '/orders/$orderId/tracking'
      fullPath: '/orders/$orderId/tracking'
      preLoaderRoute: typeof storeprotectedOrdersOrderIdTrackingRouteImport
      parentRoute: typeof storeprotectedLayoutRoute
    }
    '/(store)/(protected)/orders/$orderId/return': {
      id: '/(store)/(protected)/orders/$orderId/return'
      path: '/orders/$orderId/return'
      fullPath: '/orders/$orderId/return'
      preLoaderRoute: typeof storeprotectedOrdersOrderIdReturnRouteImport
      parentRoute: typeof storeprotectedLayoutRoute
    }
  }
}

interface storeprotectedCheckoutLayoutRouteChildren {
  storeprotectedCheckoutAddressRoute: typeof storeprotectedCheckoutAddressRoute
  storeprotectedCheckoutPaymentRoute: typeof storeprotectedCheckoutPaymentRoute
  storeprotectedCheckoutReviewRoute: typeof storeprotectedCheckoutReviewRoute
  storeprotectedCheckoutIndexRoute: typeof storeprotectedCheckoutIndexRoute
}

const storeprotectedCheckoutLayoutRouteChildren: storeprotectedCheckoutLayoutRouteChildren =
  {
    storeprotectedCheckoutAddressRoute: storeprotectedCheckoutAddressRoute,
    storeprotectedCheckoutPaymentRoute: storeprotectedCheckoutPaymentRoute,
    storeprotectedCheckoutReviewRoute: storeprotectedCheckoutReviewRoute,
    storeprotectedCheckoutIndexRoute: storeprotectedCheckoutIndexRoute,
  }

const storeprotectedCheckoutLayoutRouteWithChildren =
  storeprotectedCheckoutLayoutRoute._addFileChildren(
    storeprotectedCheckoutLayoutRouteChildren,
  )

interface storeprotectedLayoutRouteChildren {
  storeprotectedCheckoutLayoutRoute: typeof storeprotectedCheckoutLayoutRouteWithChildren
  storeprotectedAddressesRoute: typeof storeprotectedAddressesRoute
  storeprotectedNotificationsRoute: typeof storeprotectedNotificationsRoute
  storeprotectedWishlistRoute: typeof storeprotectedWishlistRoute
  storeprotectedPaymentStatusRoute: typeof storeprotectedPaymentStatusRoute
  storeprotectedOrdersIndexRoute: typeof storeprotectedOrdersIndexRoute
  storeprotectedOrdersOrderIdReturnRoute: typeof storeprotectedOrdersOrderIdReturnRoute
  storeprotectedOrdersOrderIdTrackingRoute: typeof storeprotectedOrdersOrderIdTrackingRoute
  storeprotectedOrdersOrderIdIndexRoute: typeof storeprotectedOrdersOrderIdIndexRoute
}

const storeprotectedLayoutRouteChildren: storeprotectedLayoutRouteChildren = {
  storeprotectedCheckoutLayoutRoute:
    storeprotectedCheckoutLayoutRouteWithChildren,
  storeprotectedAddressesRoute: storeprotectedAddressesRoute,
  storeprotectedNotificationsRoute: storeprotectedNotificationsRoute,
  storeprotectedWishlistRoute: storeprotectedWishlistRoute,
  storeprotectedPaymentStatusRoute: storeprotectedPaymentStatusRoute,
  storeprotectedOrdersIndexRoute: storeprotectedOrdersIndexRoute,
  storeprotectedOrdersOrderIdReturnRoute:
    storeprotectedOrdersOrderIdReturnRoute,
  storeprotectedOrdersOrderIdTrackingRoute:
    storeprotectedOrdersOrderIdTrackingRoute,
  storeprotectedOrdersOrderIdIndexRoute: storeprotectedOrdersOrderIdIndexRoute,
}

const storeprotectedLayoutRouteWithChildren =
  storeprotectedLayoutRoute._addFileChildren(storeprotectedLayoutRouteChildren)

interface storeLayoutRouteChildren {
  storeprotectedLayoutRoute: typeof storeprotectedLayoutRouteWithChildren
  storeAboutRoute: typeof storeAboutRoute
  storeCartRoute: typeof storeCartRoute
  storeContactRoute: typeof storeContactRoute
  storeHelpRoute: typeof storeHelpRoute
  storeSearchRoute: typeof storeSearchRoute
  storeIndexRoute: typeof storeIndexRoute
  storeLegalPrivacyRoute: typeof storeLegalPrivacyRoute
  storeLegalReturnsRoute: typeof storeLegalReturnsRoute
  storeLegalShippingRoute: typeof storeLegalShippingRoute
  storeLegalTermsRoute: typeof storeLegalTermsRoute
  storeProfileBabyRoute: typeof storeProfileBabyRoute
  storeProductIndexRoute: typeof storeProductIndexRoute
  storeProfileIndexRoute: typeof storeProfileIndexRoute
  storeProductProductIdReviewsRoute: typeof storeProductProductIdReviewsRoute
  storeProductProductIdIndexRoute: typeof storeProductProductIdIndexRoute
}

const storeLayoutRouteChildren: storeLayoutRouteChildren = {
  storeprotectedLayoutRoute: storeprotectedLayoutRouteWithChildren,
  storeAboutRoute: storeAboutRoute,
  storeCartRoute: storeCartRoute,
  storeContactRoute: storeContactRoute,
  storeHelpRoute: storeHelpRoute,
  storeSearchRoute: storeSearchRoute,
  storeIndexRoute: storeIndexRoute,
  storeLegalPrivacyRoute: storeLegalPrivacyRoute,
  storeLegalReturnsRoute: storeLegalReturnsRoute,
  storeLegalShippingRoute: storeLegalShippingRoute,
  storeLegalTermsRoute: storeLegalTermsRoute,
  storeProfileBabyRoute: storeProfileBabyRoute,
  storeProductIndexRoute: storeProductIndexRoute,
  storeProfileIndexRoute: storeProfileIndexRoute,
  storeProductProductIdReviewsRoute: storeProductProductIdReviewsRoute,
  storeProductProductIdIndexRoute: storeProductProductIdIndexRoute,
}

const storeLayoutRouteWithChildren = storeLayoutRoute._addFileChildren(
  storeLayoutRouteChildren,
)

interface AuthLayoutRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthOtpRoute: typeof AuthOtpRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthOtpRoute: AuthOtpRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  storeLayoutRoute: storeLayoutRouteWithChildren,
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
