/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as SearchRouteImport } from './pages/search'
import { Route as HelpRouteImport } from './pages/help'
import { Route as ContactRouteImport } from './pages/contact'
import { Route as CartRouteImport } from './pages/cart'
import { Route as AboutRouteImport } from './pages/about'
import { Route as protectedLayoutRouteImport } from './pages/(protected)/_layout'
import { Route as IndexRouteImport } from './pages/index'
import { Route as ProductIndexRouteImport } from './pages/product/index'
import { Route as LegalTermsRouteImport } from './pages/legal/terms'
import { Route as LegalShippingRouteImport } from './pages/legal/shipping'
import { Route as LegalReturnsRouteImport } from './pages/legal/returns'
import { Route as LegalPrivacyRouteImport } from './pages/legal/privacy'
import { Route as CategorySlugRouteImport } from './pages/category/$slug'
import { Route as AuthVerifyEmailRouteImport } from './pages/auth/verify-email'
import { Route as AuthResetPasswordRouteImport } from './pages/auth/reset-password'
import { Route as AuthOtpRouteImport } from './pages/auth/otp'
import { Route as AuthLoginRouteImport } from './pages/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './pages/auth/forgot-password'
import { Route as protectedWishlistRouteImport } from './pages/(protected)/wishlist'
import { Route as protectedNotificationsRouteImport } from './pages/(protected)/notifications'
import { Route as protectedAddressesRouteImport } from './pages/(protected)/addresses'
import { Route as ProductProductIdIndexRouteImport } from './pages/product/$productId/index'
import { Route as protectedSubscriptionsIndexRouteImport } from './pages/(protected)/subscriptions/index'
import { Route as protectedProfileIndexRouteImport } from './pages/(protected)/profile/index'
import { Route as protectedOrdersIndexRouteImport } from './pages/(protected)/orders/index'
import { Route as ProductProductIdReviewsRouteImport } from './pages/product/$productId/reviews'
import { Route as protectedProfileBabyRouteImport } from './pages/(protected)/profile/baby'
import { Route as protectedPaymentStatusRouteImport } from './pages/(protected)/payment/status'
import { Route as protectedCheckoutReviewRouteImport } from './pages/(protected)/checkout/review'
import { Route as protectedCheckoutPaymentRouteImport } from './pages/(protected)/checkout/payment'
import { Route as protectedCheckoutAddressRouteImport } from './pages/(protected)/checkout/address'
import { Route as protectedOrdersOrderIdIndexRouteImport } from './pages/(protected)/orders/$orderId/index'
import { Route as protectedOrdersOrderIdTrackingRouteImport } from './pages/(protected)/orders/$orderId/tracking'
import { Route as protectedOrdersOrderIdReturnRouteImport } from './pages/(protected)/orders/$orderId/return'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedLayoutRoute = protectedLayoutRouteImport.update({
  id: '/(protected)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIndexRoute = ProductIndexRouteImport.update({
  id: '/product/',
  path: '/product/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalShippingRoute = LegalShippingRouteImport.update({
  id: '/legal/shipping',
  path: '/legal/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalReturnsRoute = LegalReturnsRouteImport.update({
  id: '/legal/returns',
  path: '/legal/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/auth/verify-email',
  path: '/auth/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthOtpRoute = AuthOtpRouteImport.update({
  id: '/auth/otp',
  path: '/auth/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedWishlistRoute = protectedWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => protectedLayoutRoute,
} as any)
const protectedNotificationsRoute = protectedNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => protectedLayoutRoute,
} as any)
const protectedAddressesRoute = protectedAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => protectedLayoutRoute,
} as any)
const ProductProductIdIndexRoute = ProductProductIdIndexRouteImport.update({
  id: '/product/$productId/',
  path: '/product/$productId/',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedSubscriptionsIndexRoute =
  protectedSubscriptionsIndexRouteImport.update({
    id: '/subscriptions/',
    path: '/subscriptions/',
    getParentRoute: () => protectedLayoutRoute,
  } as any)
const protectedProfileIndexRoute = protectedProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => protectedLayoutRoute,
} as any)
const protectedOrdersIndexRoute = protectedOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => protectedLayoutRoute,
} as any)
const ProductProductIdReviewsRoute = ProductProductIdReviewsRouteImport.update({
  id: '/product/$productId/reviews',
  path: '/product/$productId/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedProfileBabyRoute = protectedProfileBabyRouteImport.update({
  id: '/profile/baby',
  path: '/profile/baby',
  getParentRoute: () => protectedLayoutRoute,
} as any)
const protectedPaymentStatusRoute = protectedPaymentStatusRouteImport.update({
  id: '/payment/status',
  path: '/payment/status',
  getParentRoute: () => protectedLayoutRoute,
} as any)
const protectedCheckoutReviewRoute = protectedCheckoutReviewRouteImport.update({
  id: '/checkout/review',
  path: '/checkout/review',
  getParentRoute: () => protectedLayoutRoute,
} as any)
const protectedCheckoutPaymentRoute =
  protectedCheckoutPaymentRouteImport.update({
    id: '/checkout/payment',
    path: '/checkout/payment',
    getParentRoute: () => protectedLayoutRoute,
  } as any)
const protectedCheckoutAddressRoute =
  protectedCheckoutAddressRouteImport.update({
    id: '/checkout/address',
    path: '/checkout/address',
    getParentRoute: () => protectedLayoutRoute,
  } as any)
const protectedOrdersOrderIdIndexRoute =
  protectedOrdersOrderIdIndexRouteImport.update({
    id: '/orders/$orderId/',
    path: '/orders/$orderId/',
    getParentRoute: () => protectedLayoutRoute,
  } as any)
const protectedOrdersOrderIdTrackingRoute =
  protectedOrdersOrderIdTrackingRouteImport.update({
    id: '/orders/$orderId/tracking',
    path: '/orders/$orderId/tracking',
    getParentRoute: () => protectedLayoutRoute,
  } as any)
const protectedOrdersOrderIdReturnRoute =
  protectedOrdersOrderIdReturnRouteImport.update({
    id: '/orders/$orderId/return',
    path: '/orders/$orderId/return',
    getParentRoute: () => protectedLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/help': typeof HelpRoute
  '/search': typeof SearchRoute
  '/addresses': typeof protectedAddressesRoute
  '/notifications': typeof protectedNotificationsRoute
  '/wishlist': typeof protectedWishlistRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/category/$slug': typeof CategorySlugRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/returns': typeof LegalReturnsRoute
  '/legal/shipping': typeof LegalShippingRoute
  '/legal/terms': typeof LegalTermsRoute
  '/product/': typeof ProductIndexRoute
  '/checkout/address': typeof protectedCheckoutAddressRoute
  '/checkout/payment': typeof protectedCheckoutPaymentRoute
  '/checkout/review': typeof protectedCheckoutReviewRoute
  '/payment/status': typeof protectedPaymentStatusRoute
  '/profile/baby': typeof protectedProfileBabyRoute
  '/product/$productId/reviews': typeof ProductProductIdReviewsRoute
  '/orders/': typeof protectedOrdersIndexRoute
  '/profile/': typeof protectedProfileIndexRoute
  '/subscriptions/': typeof protectedSubscriptionsIndexRoute
  '/product/$productId/': typeof ProductProductIdIndexRoute
  '/orders/$orderId/return': typeof protectedOrdersOrderIdReturnRoute
  '/orders/$orderId/tracking': typeof protectedOrdersOrderIdTrackingRoute
  '/orders/$orderId/': typeof protectedOrdersOrderIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/help': typeof HelpRoute
  '/search': typeof SearchRoute
  '/addresses': typeof protectedAddressesRoute
  '/notifications': typeof protectedNotificationsRoute
  '/wishlist': typeof protectedWishlistRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/category/$slug': typeof CategorySlugRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/returns': typeof LegalReturnsRoute
  '/legal/shipping': typeof LegalShippingRoute
  '/legal/terms': typeof LegalTermsRoute
  '/product': typeof ProductIndexRoute
  '/checkout/address': typeof protectedCheckoutAddressRoute
  '/checkout/payment': typeof protectedCheckoutPaymentRoute
  '/checkout/review': typeof protectedCheckoutReviewRoute
  '/payment/status': typeof protectedPaymentStatusRoute
  '/profile/baby': typeof protectedProfileBabyRoute
  '/product/$productId/reviews': typeof ProductProductIdReviewsRoute
  '/orders': typeof protectedOrdersIndexRoute
  '/profile': typeof protectedProfileIndexRoute
  '/subscriptions': typeof protectedSubscriptionsIndexRoute
  '/product/$productId': typeof ProductProductIdIndexRoute
  '/orders/$orderId/return': typeof protectedOrdersOrderIdReturnRoute
  '/orders/$orderId/tracking': typeof protectedOrdersOrderIdTrackingRoute
  '/orders/$orderId': typeof protectedOrdersOrderIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(protected)': typeof protectedLayoutRouteWithChildren
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/help': typeof HelpRoute
  '/search': typeof SearchRoute
  '/(protected)/addresses': typeof protectedAddressesRoute
  '/(protected)/notifications': typeof protectedNotificationsRoute
  '/(protected)/wishlist': typeof protectedWishlistRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/category/$slug': typeof CategorySlugRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/returns': typeof LegalReturnsRoute
  '/legal/shipping': typeof LegalShippingRoute
  '/legal/terms': typeof LegalTermsRoute
  '/product/': typeof ProductIndexRoute
  '/(protected)/checkout/address': typeof protectedCheckoutAddressRoute
  '/(protected)/checkout/payment': typeof protectedCheckoutPaymentRoute
  '/(protected)/checkout/review': typeof protectedCheckoutReviewRoute
  '/(protected)/payment/status': typeof protectedPaymentStatusRoute
  '/(protected)/profile/baby': typeof protectedProfileBabyRoute
  '/product/$productId/reviews': typeof ProductProductIdReviewsRoute
  '/(protected)/orders/': typeof protectedOrdersIndexRoute
  '/(protected)/profile/': typeof protectedProfileIndexRoute
  '/(protected)/subscriptions/': typeof protectedSubscriptionsIndexRoute
  '/product/$productId/': typeof ProductProductIdIndexRoute
  '/(protected)/orders/$orderId/return': typeof protectedOrdersOrderIdReturnRoute
  '/(protected)/orders/$orderId/tracking': typeof protectedOrdersOrderIdTrackingRoute
  '/(protected)/orders/$orderId/': typeof protectedOrdersOrderIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cart'
    | '/contact'
    | '/help'
    | '/search'
    | '/addresses'
    | '/notifications'
    | '/wishlist'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/otp'
    | '/auth/reset-password'
    | '/auth/verify-email'
    | '/category/$slug'
    | '/legal/privacy'
    | '/legal/returns'
    | '/legal/shipping'
    | '/legal/terms'
    | '/product/'
    | '/checkout/address'
    | '/checkout/payment'
    | '/checkout/review'
    | '/payment/status'
    | '/profile/baby'
    | '/product/$productId/reviews'
    | '/orders/'
    | '/profile/'
    | '/subscriptions/'
    | '/product/$productId/'
    | '/orders/$orderId/return'
    | '/orders/$orderId/tracking'
    | '/orders/$orderId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/contact'
    | '/help'
    | '/search'
    | '/addresses'
    | '/notifications'
    | '/wishlist'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/otp'
    | '/auth/reset-password'
    | '/auth/verify-email'
    | '/category/$slug'
    | '/legal/privacy'
    | '/legal/returns'
    | '/legal/shipping'
    | '/legal/terms'
    | '/product'
    | '/checkout/address'
    | '/checkout/payment'
    | '/checkout/review'
    | '/payment/status'
    | '/profile/baby'
    | '/product/$productId/reviews'
    | '/orders'
    | '/profile'
    | '/subscriptions'
    | '/product/$productId'
    | '/orders/$orderId/return'
    | '/orders/$orderId/tracking'
    | '/orders/$orderId'
  id:
    | '__root__'
    | '/'
    | '/(protected)'
    | '/about'
    | '/cart'
    | '/contact'
    | '/help'
    | '/search'
    | '/(protected)/addresses'
    | '/(protected)/notifications'
    | '/(protected)/wishlist'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/otp'
    | '/auth/reset-password'
    | '/auth/verify-email'
    | '/category/$slug'
    | '/legal/privacy'
    | '/legal/returns'
    | '/legal/shipping'
    | '/legal/terms'
    | '/product/'
    | '/(protected)/checkout/address'
    | '/(protected)/checkout/payment'
    | '/(protected)/checkout/review'
    | '/(protected)/payment/status'
    | '/(protected)/profile/baby'
    | '/product/$productId/reviews'
    | '/(protected)/orders/'
    | '/(protected)/profile/'
    | '/(protected)/subscriptions/'
    | '/product/$productId/'
    | '/(protected)/orders/$orderId/return'
    | '/(protected)/orders/$orderId/tracking'
    | '/(protected)/orders/$orderId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  protectedLayoutRoute: typeof protectedLayoutRouteWithChildren
  AboutRoute: typeof AboutRoute
  CartRoute: typeof CartRoute
  ContactRoute: typeof ContactRoute
  HelpRoute: typeof HelpRoute
  SearchRoute: typeof SearchRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthOtpRoute: typeof AuthOtpRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
  CategorySlugRoute: typeof CategorySlugRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalReturnsRoute: typeof LegalReturnsRoute
  LegalShippingRoute: typeof LegalShippingRoute
  LegalTermsRoute: typeof LegalTermsRoute
  ProductIndexRoute: typeof ProductIndexRoute
  ProductProductIdReviewsRoute: typeof ProductProductIdReviewsRoute
  ProductProductIdIndexRoute: typeof ProductProductIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)': {
      id: '/(protected)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof protectedLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/': {
      id: '/product/'
      path: '/product'
      fullPath: '/product/'
      preLoaderRoute: typeof ProductIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/shipping': {
      id: '/legal/shipping'
      path: '/legal/shipping'
      fullPath: '/legal/shipping'
      preLoaderRoute: typeof LegalShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/returns': {
      id: '/legal/returns'
      path: '/legal/returns'
      fullPath: '/legal/returns'
      preLoaderRoute: typeof LegalReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-email': {
      id: '/auth/verify-email'
      path: '/auth/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/otp': {
      id: '/auth/otp'
      path: '/auth/otp'
      fullPath: '/auth/otp'
      preLoaderRoute: typeof AuthOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/wishlist': {
      id: '/(protected)/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof protectedWishlistRouteImport
      parentRoute: typeof protectedLayoutRoute
    }
    '/(protected)/notifications': {
      id: '/(protected)/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof protectedNotificationsRouteImport
      parentRoute: typeof protectedLayoutRoute
    }
    '/(protected)/addresses': {
      id: '/(protected)/addresses'
      path: '/addresses'
      fullPath: '/addresses'
      preLoaderRoute: typeof protectedAddressesRouteImport
      parentRoute: typeof protectedLayoutRoute
    }
    '/product/$productId/': {
      id: '/product/$productId/'
      path: '/product/$productId'
      fullPath: '/product/$productId/'
      preLoaderRoute: typeof ProductProductIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/subscriptions/': {
      id: '/(protected)/subscriptions/'
      path: '/subscriptions'
      fullPath: '/subscriptions/'
      preLoaderRoute: typeof protectedSubscriptionsIndexRouteImport
      parentRoute: typeof protectedLayoutRoute
    }
    '/(protected)/profile/': {
      id: '/(protected)/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof protectedProfileIndexRouteImport
      parentRoute: typeof protectedLayoutRoute
    }
    '/(protected)/orders/': {
      id: '/(protected)/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof protectedOrdersIndexRouteImport
      parentRoute: typeof protectedLayoutRoute
    }
    '/product/$productId/reviews': {
      id: '/product/$productId/reviews'
      path: '/product/$productId/reviews'
      fullPath: '/product/$productId/reviews'
      preLoaderRoute: typeof ProductProductIdReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/profile/baby': {
      id: '/(protected)/profile/baby'
      path: '/profile/baby'
      fullPath: '/profile/baby'
      preLoaderRoute: typeof protectedProfileBabyRouteImport
      parentRoute: typeof protectedLayoutRoute
    }
    '/(protected)/payment/status': {
      id: '/(protected)/payment/status'
      path: '/payment/status'
      fullPath: '/payment/status'
      preLoaderRoute: typeof protectedPaymentStatusRouteImport
      parentRoute: typeof protectedLayoutRoute
    }
    '/(protected)/checkout/review': {
      id: '/(protected)/checkout/review'
      path: '/checkout/review'
      fullPath: '/checkout/review'
      preLoaderRoute: typeof protectedCheckoutReviewRouteImport
      parentRoute: typeof protectedLayoutRoute
    }
    '/(protected)/checkout/payment': {
      id: '/(protected)/checkout/payment'
      path: '/checkout/payment'
      fullPath: '/checkout/payment'
      preLoaderRoute: typeof protectedCheckoutPaymentRouteImport
      parentRoute: typeof protectedLayoutRoute
    }
    '/(protected)/checkout/address': {
      id: '/(protected)/checkout/address'
      path: '/checkout/address'
      fullPath: '/checkout/address'
      preLoaderRoute: typeof protectedCheckoutAddressRouteImport
      parentRoute: typeof protectedLayoutRoute
    }
    '/(protected)/orders/$orderId/': {
      id: '/(protected)/orders/$orderId/'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId/'
      preLoaderRoute: typeof protectedOrdersOrderIdIndexRouteImport
      parentRoute: typeof protectedLayoutRoute
    }
    '/(protected)/orders/$orderId/tracking': {
      id: '/(protected)/orders/$orderId/tracking'
      path: '/orders/$orderId/tracking'
      fullPath: '/orders/$orderId/tracking'
      preLoaderRoute: typeof protectedOrdersOrderIdTrackingRouteImport
      parentRoute: typeof protectedLayoutRoute
    }
    '/(protected)/orders/$orderId/return': {
      id: '/(protected)/orders/$orderId/return'
      path: '/orders/$orderId/return'
      fullPath: '/orders/$orderId/return'
      preLoaderRoute: typeof protectedOrdersOrderIdReturnRouteImport
      parentRoute: typeof protectedLayoutRoute
    }
  }
}

interface protectedLayoutRouteChildren {
  protectedAddressesRoute: typeof protectedAddressesRoute
  protectedNotificationsRoute: typeof protectedNotificationsRoute
  protectedWishlistRoute: typeof protectedWishlistRoute
  protectedCheckoutAddressRoute: typeof protectedCheckoutAddressRoute
  protectedCheckoutPaymentRoute: typeof protectedCheckoutPaymentRoute
  protectedCheckoutReviewRoute: typeof protectedCheckoutReviewRoute
  protectedPaymentStatusRoute: typeof protectedPaymentStatusRoute
  protectedProfileBabyRoute: typeof protectedProfileBabyRoute
  protectedOrdersIndexRoute: typeof protectedOrdersIndexRoute
  protectedProfileIndexRoute: typeof protectedProfileIndexRoute
  protectedSubscriptionsIndexRoute: typeof protectedSubscriptionsIndexRoute
  protectedOrdersOrderIdReturnRoute: typeof protectedOrdersOrderIdReturnRoute
  protectedOrdersOrderIdTrackingRoute: typeof protectedOrdersOrderIdTrackingRoute
  protectedOrdersOrderIdIndexRoute: typeof protectedOrdersOrderIdIndexRoute
}

const protectedLayoutRouteChildren: protectedLayoutRouteChildren = {
  protectedAddressesRoute: protectedAddressesRoute,
  protectedNotificationsRoute: protectedNotificationsRoute,
  protectedWishlistRoute: protectedWishlistRoute,
  protectedCheckoutAddressRoute: protectedCheckoutAddressRoute,
  protectedCheckoutPaymentRoute: protectedCheckoutPaymentRoute,
  protectedCheckoutReviewRoute: protectedCheckoutReviewRoute,
  protectedPaymentStatusRoute: protectedPaymentStatusRoute,
  protectedProfileBabyRoute: protectedProfileBabyRoute,
  protectedOrdersIndexRoute: protectedOrdersIndexRoute,
  protectedProfileIndexRoute: protectedProfileIndexRoute,
  protectedSubscriptionsIndexRoute: protectedSubscriptionsIndexRoute,
  protectedOrdersOrderIdReturnRoute: protectedOrdersOrderIdReturnRoute,
  protectedOrdersOrderIdTrackingRoute: protectedOrdersOrderIdTrackingRoute,
  protectedOrdersOrderIdIndexRoute: protectedOrdersOrderIdIndexRoute,
}

const protectedLayoutRouteWithChildren = protectedLayoutRoute._addFileChildren(
  protectedLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  protectedLayoutRoute: protectedLayoutRouteWithChildren,
  AboutRoute: AboutRoute,
  CartRoute: CartRoute,
  ContactRoute: ContactRoute,
  HelpRoute: HelpRoute,
  SearchRoute: SearchRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthOtpRoute: AuthOtpRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
  CategorySlugRoute: CategorySlugRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalReturnsRoute: LegalReturnsRoute,
  LegalShippingRoute: LegalShippingRoute,
  LegalTermsRoute: LegalTermsRoute,
  ProductIndexRoute: ProductIndexRoute,
  ProductProductIdReviewsRoute: ProductProductIdReviewsRoute,
  ProductProductIdIndexRoute: ProductProductIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
