/**
 * Machine-readable error codes.
 *
 * Clients switch on these, so treat them as API surface: adding is safe,
 * renaming is a breaking change. `apps/admin/src/core/api/client.ts` types
 * the field as `| (string & {})`, so new codes do not break its build.
 */
export const ERROR_CODES = {
  // Generic
  VALIDATION_ERROR: "VALIDATION_ERROR",
  NOT_FOUND: "NOT_FOUND",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  CONFLICT: "CONFLICT",
  RATE_LIMITED: "RATE_LIMITED",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",

  // Domain — from docs/api/mumzo_api_plan.md
  PRODUCT_OUT_OF_STOCK: "PRODUCT_OUT_OF_STOCK",
  COUPON_EXPIRED: "COUPON_EXPIRED",
  COUPON_INVALID: "COUPON_INVALID",
  COUPON_MIN_AMOUNT: "COUPON_MIN_AMOUNT",
  COUPON_EXHAUSTED: "COUPON_EXHAUSTED",
  ORDER_NOT_CANCELLABLE: "ORDER_NOT_CANCELLABLE",
  PAYMENT_FAILED: "PAYMENT_FAILED",
  REFERRAL_CODE_INVALID: "REFERRAL_CODE_INVALID",
  REFERRAL_SELF_REFERRAL: "REFERRAL_SELF_REFERRAL",
  REFERRAL_COUPON_NOT_YOURS: "REFERRAL_COUPON_NOT_YOURS",
  COUPON_FIRST_ORDER_ONLY: "COUPON_FIRST_ORDER_ONLY",
  COUPON_ALREADY_USED_BY_YOU: "COUPON_ALREADY_USED_BY_YOU",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
