/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as LoginRouteImport } from './pages/login'
import { Route as ForbiddenRouteImport } from './pages/forbidden'
import { Route as adminLayoutRouteImport } from './pages/(admin)/_layout'
import { Route as adminIndexRouteImport } from './pages/(admin)/index'
import { Route as adminStaffIndexRouteImport } from './pages/(admin)/staff/index'
import { Route as adminStaffAuditLogRouteImport } from './pages/(admin)/staff/audit-log'
import { Route as adminPlatformSystemRouteImport } from './pages/(admin)/platform/system'
import { Route as adminPlatformIntegrationsRouteImport } from './pages/(admin)/platform/integrations'
import { Route as adminPlatformFlagsRouteImport } from './pages/(admin)/platform/flags'
import { Route as adminPlatformExperimentsRouteImport } from './pages/(admin)/platform/experiments'
import { Route as adminOverviewOpsRouteImport } from './pages/(admin)/overview/ops'
import { Route as adminOverviewBiRouteImport } from './pages/(admin)/overview/bi'
import { Route as adminOverviewAnalyticsRouteImport } from './pages/(admin)/overview/analytics'
import { Route as adminOperationsReturnsRouteImport } from './pages/(admin)/operations/returns'
import { Route as adminOperationsDispatchRouteImport } from './pages/(admin)/operations/dispatch'
import { Route as adminLegalConfigRouteImport } from './pages/(admin)/legal/config'
import { Route as adminLegalBannersRouteImport } from './pages/(admin)/legal/banners'
import { Route as adminFinanceTaxRouteImport } from './pages/(admin)/finance/tax'
import { Route as adminFinanceReconciliationRouteImport } from './pages/(admin)/finance/reconciliation'
import { Route as adminFinanceCampaignsRouteImport } from './pages/(admin)/finance/campaigns'
import { Route as adminCustomersSegmentsRouteImport } from './pages/(admin)/customers/segments'
import { Route as adminCustomersReviewsRouteImport } from './pages/(admin)/customers/reviews'
import { Route as adminCustomersJourneysRouteImport } from './pages/(admin)/customers/journeys'
import { Route as adminCatalogPricingRouteImport } from './pages/(admin)/catalog/pricing'
import { Route as adminCatalogMerchandisingRouteImport } from './pages/(admin)/catalog/merchandising'
import { Route as adminCatalogHubsRouteImport } from './pages/(admin)/catalog/hubs'
import { Route as adminCatalogCollectionsRouteImport } from './pages/(admin)/catalog/collections'
import { Route as adminCatalogBrandsRouteImport } from './pages/(admin)/catalog/brands'
import { Route as adminOperationsTicketsIndexRouteImport } from './pages/(admin)/operations/tickets/index'
import { Route as adminOperationsRidersIndexRouteImport } from './pages/(admin)/operations/riders/index'
import { Route as adminOperationsOrdersIndexRouteImport } from './pages/(admin)/operations/orders/index'
import { Route as adminLegalPagesIndexRouteImport } from './pages/(admin)/legal/pages/index'
import { Route as adminFinanceSubscriptionsIndexRouteImport } from './pages/(admin)/finance/subscriptions/index'
import { Route as adminFinancePaymentsIndexRouteImport } from './pages/(admin)/finance/payments/index'
import { Route as adminFinanceCouponsIndexRouteImport } from './pages/(admin)/finance/coupons/index'
import { Route as adminCustomersUsersIndexRouteImport } from './pages/(admin)/customers/users/index'
import { Route as adminCustomersBroadcastsIndexRouteImport } from './pages/(admin)/customers/broadcasts/index'
import { Route as adminCatalogProductsIndexRouteImport } from './pages/(admin)/catalog/products/index'
import { Route as adminCatalogInventoryIndexRouteImport } from './pages/(admin)/catalog/inventory/index'
import { Route as adminCatalogCategoriesIndexRouteImport } from './pages/(admin)/catalog/categories/index'
import { Route as adminOperationsTicketsTicketIdRouteImport } from './pages/(admin)/operations/tickets/$ticketId'
import { Route as adminOperationsRidersRiderIdRouteImport } from './pages/(admin)/operations/riders/$riderId'
import { Route as adminOperationsOrdersOrderIdRouteImport } from './pages/(admin)/operations/orders/$orderId'
import { Route as adminLegalPagesPageSlugRouteImport } from './pages/(admin)/legal/pages/$pageSlug'
import { Route as adminFinanceSubscriptionsUpcomingRouteImport } from './pages/(admin)/finance/subscriptions/upcoming'
import { Route as adminFinancePaymentsFailedRouteImport } from './pages/(admin)/finance/payments/failed'
import { Route as adminFinancePaymentsPaymentIdRouteImport } from './pages/(admin)/finance/payments/$paymentId'
import { Route as adminFinanceCouponsNewRouteImport } from './pages/(admin)/finance/coupons/new'
import { Route as adminFinanceCouponsCouponIdRouteImport } from './pages/(admin)/finance/coupons/$couponId'
import { Route as adminCustomersUsersUserIdRouteImport } from './pages/(admin)/customers/users/$userId'
import { Route as adminCustomersBroadcastsNewRouteImport } from './pages/(admin)/customers/broadcasts/new'
import { Route as adminCatalogProductsNewRouteImport } from './pages/(admin)/catalog/products/new'
import { Route as adminCatalogProductsBulkRouteImport } from './pages/(admin)/catalog/products/bulk'
import { Route as adminCatalogInventoryBatchesRouteImport } from './pages/(admin)/catalog/inventory/batches'
import { Route as adminCatalogInventoryAdjustmentsRouteImport } from './pages/(admin)/catalog/inventory/adjustments'
import { Route as adminCatalogCategoriesNewRouteImport } from './pages/(admin)/catalog/categories/new'
import { Route as adminCatalogCategoriesSlugRouteImport } from './pages/(admin)/catalog/categories/$slug'
import { Route as adminCatalogProductsProductIdIndexRouteImport } from './pages/(admin)/catalog/products/$productId/index'
import { Route as adminCatalogProductsProductIdStockRouteImport } from './pages/(admin)/catalog/products/$productId/stock'
import { Route as adminCatalogProductsProductIdImagesRouteImport } from './pages/(admin)/catalog/products/$productId/images'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForbiddenRoute = ForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const adminLayoutRoute = adminLayoutRouteImport.update({
  id: '/(admin)',
  getParentRoute: () => rootRouteImport,
} as any)
const adminIndexRoute = adminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminStaffIndexRoute = adminStaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminStaffAuditLogRoute = adminStaffAuditLogRouteImport.update({
  id: '/staff/audit-log',
  path: '/staff/audit-log',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminPlatformSystemRoute = adminPlatformSystemRouteImport.update({
  id: '/platform/system',
  path: '/platform/system',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminPlatformIntegrationsRoute =
  adminPlatformIntegrationsRouteImport.update({
    id: '/platform/integrations',
    path: '/platform/integrations',
    getParentRoute: () => adminLayoutRoute,
  } as any)
const adminPlatformFlagsRoute = adminPlatformFlagsRouteImport.update({
  id: '/platform/flags',
  path: '/platform/flags',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminPlatformExperimentsRoute =
  adminPlatformExperimentsRouteImport.update({
    id: '/platform/experiments',
    path: '/platform/experiments',
    getParentRoute: () => adminLayoutRoute,
  } as any)
const adminOverviewOpsRoute = adminOverviewOpsRouteImport.update({
  id: '/overview/ops',
  path: '/overview/ops',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminOverviewBiRoute = adminOverviewBiRouteImport.update({
  id: '/overview/bi',
  path: '/overview/bi',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminOverviewAnalyticsRoute = adminOverviewAnalyticsRouteImport.update({
  id: '/overview/analytics',
  path: '/overview/analytics',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminOperationsReturnsRoute = adminOperationsReturnsRouteImport.update({
  id: '/operations/returns',
  path: '/operations/returns',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminOperationsDispatchRoute = adminOperationsDispatchRouteImport.update({
  id: '/operations/dispatch',
  path: '/operations/dispatch',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminLegalConfigRoute = adminLegalConfigRouteImport.update({
  id: '/legal/config',
  path: '/legal/config',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminLegalBannersRoute = adminLegalBannersRouteImport.update({
  id: '/legal/banners',
  path: '/legal/banners',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminFinanceTaxRoute = adminFinanceTaxRouteImport.update({
  id: '/finance/tax',
  path: '/finance/tax',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminFinanceReconciliationRoute =
  adminFinanceReconciliationRouteImport.update({
    id: '/finance/reconciliation',
    path: '/finance/reconciliation',
    getParentRoute: () => adminLayoutRoute,
  } as any)
const adminFinanceCampaignsRoute = adminFinanceCampaignsRouteImport.update({
  id: '/finance/campaigns',
  path: '/finance/campaigns',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminCustomersSegmentsRoute = adminCustomersSegmentsRouteImport.update({
  id: '/customers/segments',
  path: '/customers/segments',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminCustomersReviewsRoute = adminCustomersReviewsRouteImport.update({
  id: '/customers/reviews',
  path: '/customers/reviews',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminCustomersJourneysRoute = adminCustomersJourneysRouteImport.update({
  id: '/customers/journeys',
  path: '/customers/journeys',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminCatalogPricingRoute = adminCatalogPricingRouteImport.update({
  id: '/catalog/pricing',
  path: '/catalog/pricing',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminCatalogMerchandisingRoute =
  adminCatalogMerchandisingRouteImport.update({
    id: '/catalog/merchandising',
    path: '/catalog/merchandising',
    getParentRoute: () => adminLayoutRoute,
  } as any)
const adminCatalogHubsRoute = adminCatalogHubsRouteImport.update({
  id: '/catalog/hubs',
  path: '/catalog/hubs',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminCatalogCollectionsRoute = adminCatalogCollectionsRouteImport.update({
  id: '/catalog/collections',
  path: '/catalog/collections',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminCatalogBrandsRoute = adminCatalogBrandsRouteImport.update({
  id: '/catalog/brands',
  path: '/catalog/brands',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminOperationsTicketsIndexRoute =
  adminOperationsTicketsIndexRouteImport.update({
    id: '/operations/tickets/',
    path: '/operations/tickets/',
    getParentRoute: () => adminLayoutRoute,
  } as any)
const adminOperationsRidersIndexRoute =
  adminOperationsRidersIndexRouteImport.update({
    id: '/operations/riders/',
    path: '/operations/riders/',
    getParentRoute: () => adminLayoutRoute,
  } as any)
const adminOperationsOrdersIndexRoute =
  adminOperationsOrdersIndexRouteImport.update({
    id: '/operations/orders/',
    path: '/operations/orders/',
    getParentRoute: () => adminLayoutRoute,
  } as any)
const adminLegalPagesIndexRoute = adminLegalPagesIndexRouteImport.update({
  id: '/legal/pages/',
  path: '/legal/pages/',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminFinanceSubscriptionsIndexRoute =
  adminFinanceSubscriptionsIndexRouteImport.update({
    id: '/finance/subscriptions/',
    path: '/finance/subscriptions/',
    getParentRoute: () => adminLayoutRoute,
  } as any)
const adminFinancePaymentsIndexRoute =
  adminFinancePaymentsIndexRouteImport.update({
    id: '/finance/payments/',
    path: '/finance/payments/',
    getParentRoute: () => adminLayoutRoute,
  } as any)
const adminFinanceCouponsIndexRoute =
  adminFinanceCouponsIndexRouteImport.update({
    id: '/finance/coupons/',
    path: '/finance/coupons/',
    getParentRoute: () => adminLayoutRoute,
  } as any)
const adminCustomersUsersIndexRoute =
  adminCustomersUsersIndexRouteImport.update({
    id: '/customers/users/',
    path: '/customers/users/',
    getParentRoute: () => adminLayoutRoute,
  } as any)
const adminCustomersBroadcastsIndexRoute =
  adminCustomersBroadcastsIndexRouteImport.update({
    id: '/customers/broadcasts/',
    path: '/customers/broadcasts/',
    getParentRoute: () => adminLayoutRoute,
  } as any)
const adminCatalogProductsIndexRoute =
  adminCatalogProductsIndexRouteImport.update({
    id: '/catalog/products/',
    path: '/catalog/products/',
    getParentRoute: () => adminLayoutRoute,
  } as any)
const adminCatalogInventoryIndexRoute =
  adminCatalogInventoryIndexRouteImport.update({
    id: '/catalog/inventory/',
    path: '/catalog/inventory/',
    getParentRoute: () => adminLayoutRoute,
  } as any)
const adminCatalogCategoriesIndexRoute =
  adminCatalogCategoriesIndexRouteImport.update({
    id: '/catalog/categories/',
    path: '/catalog/categories/',
    getParentRoute: () => adminLayoutRoute,
  } as any)
const adminOperationsTicketsTicketIdRoute =
  adminOperationsTicketsTicketIdRouteImport.update({
    id: '/operations/tickets/$ticketId',
    path: '/operations/tickets/$ticketId',
    getParentRoute: () => adminLayoutRoute,
  } as any)
const adminOperationsRidersRiderIdRoute =
  adminOperationsRidersRiderIdRouteImport.update({
    id: '/operations/riders/$riderId',
    path: '/operations/riders/$riderId',
    getParentRoute: () => adminLayoutRoute,
  } as any)
const adminOperationsOrdersOrderIdRoute =
  adminOperationsOrdersOrderIdRouteImport.update({
    id: '/operations/orders/$orderId',
    path: '/operations/orders/$orderId',
    getParentRoute: () => adminLayoutRoute,
  } as any)
const adminLegalPagesPageSlugRoute = adminLegalPagesPageSlugRouteImport.update({
  id: '/legal/pages/$pageSlug',
  path: '/legal/pages/$pageSlug',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminFinanceSubscriptionsUpcomingRoute =
  adminFinanceSubscriptionsUpcomingRouteImport.update({
    id: '/finance/subscriptions/upcoming',
    path: '/finance/subscriptions/upcoming',
    getParentRoute: () => adminLayoutRoute,
  } as any)
const adminFinancePaymentsFailedRoute =
  adminFinancePaymentsFailedRouteImport.update({
    id: '/finance/payments/failed',
    path: '/finance/payments/failed',
    getParentRoute: () => adminLayoutRoute,
  } as any)
const adminFinancePaymentsPaymentIdRoute =
  adminFinancePaymentsPaymentIdRouteImport.update({
    id: '/finance/payments/$paymentId',
    path: '/finance/payments/$paymentId',
    getParentRoute: () => adminLayoutRoute,
  } as any)
const adminFinanceCouponsNewRoute = adminFinanceCouponsNewRouteImport.update({
  id: '/finance/coupons/new',
  path: '/finance/coupons/new',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminFinanceCouponsCouponIdRoute =
  adminFinanceCouponsCouponIdRouteImport.update({
    id: '/finance/coupons/$couponId',
    path: '/finance/coupons/$couponId',
    getParentRoute: () => adminLayoutRoute,
  } as any)
const adminCustomersUsersUserIdRoute =
  adminCustomersUsersUserIdRouteImport.update({
    id: '/customers/users/$userId',
    path: '/customers/users/$userId',
    getParentRoute: () => adminLayoutRoute,
  } as any)
const adminCustomersBroadcastsNewRoute =
  adminCustomersBroadcastsNewRouteImport.update({
    id: '/customers/broadcasts/new',
    path: '/customers/broadcasts/new',
    getParentRoute: () => adminLayoutRoute,
  } as any)
const adminCatalogProductsNewRoute = adminCatalogProductsNewRouteImport.update({
  id: '/catalog/products/new',
  path: '/catalog/products/new',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminCatalogProductsBulkRoute =
  adminCatalogProductsBulkRouteImport.update({
    id: '/catalog/products/bulk',
    path: '/catalog/products/bulk',
    getParentRoute: () => adminLayoutRoute,
  } as any)
const adminCatalogInventoryBatchesRoute =
  adminCatalogInventoryBatchesRouteImport.update({
    id: '/catalog/inventory/batches',
    path: '/catalog/inventory/batches',
    getParentRoute: () => adminLayoutRoute,
  } as any)
const adminCatalogInventoryAdjustmentsRoute =
  adminCatalogInventoryAdjustmentsRouteImport.update({
    id: '/catalog/inventory/adjustments',
    path: '/catalog/inventory/adjustments',
    getParentRoute: () => adminLayoutRoute,
  } as any)
const adminCatalogCategoriesNewRoute =
  adminCatalogCategoriesNewRouteImport.update({
    id: '/catalog/categories/new',
    path: '/catalog/categories/new',
    getParentRoute: () => adminLayoutRoute,
  } as any)
const adminCatalogCategoriesSlugRoute =
  adminCatalogCategoriesSlugRouteImport.update({
    id: '/catalog/categories/$slug',
    path: '/catalog/categories/$slug',
    getParentRoute: () => adminLayoutRoute,
  } as any)
const adminCatalogProductsProductIdIndexRoute =
  adminCatalogProductsProductIdIndexRouteImport.update({
    id: '/catalog/products/$productId/',
    path: '/catalog/products/$productId/',
    getParentRoute: () => adminLayoutRoute,
  } as any)
const adminCatalogProductsProductIdStockRoute =
  adminCatalogProductsProductIdStockRouteImport.update({
    id: '/catalog/products/$productId/stock',
    path: '/catalog/products/$productId/stock',
    getParentRoute: () => adminLayoutRoute,
  } as any)
const adminCatalogProductsProductIdImagesRoute =
  adminCatalogProductsProductIdImagesRouteImport.update({
    id: '/catalog/products/$productId/images',
    path: '/catalog/products/$productId/images',
    getParentRoute: () => adminLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/': typeof adminIndexRoute
  '/catalog/brands': typeof adminCatalogBrandsRoute
  '/catalog/collections': typeof adminCatalogCollectionsRoute
  '/catalog/hubs': typeof adminCatalogHubsRoute
  '/catalog/merchandising': typeof adminCatalogMerchandisingRoute
  '/catalog/pricing': typeof adminCatalogPricingRoute
  '/customers/journeys': typeof adminCustomersJourneysRoute
  '/customers/reviews': typeof adminCustomersReviewsRoute
  '/customers/segments': typeof adminCustomersSegmentsRoute
  '/finance/campaigns': typeof adminFinanceCampaignsRoute
  '/finance/reconciliation': typeof adminFinanceReconciliationRoute
  '/finance/tax': typeof adminFinanceTaxRoute
  '/legal/banners': typeof adminLegalBannersRoute
  '/legal/config': typeof adminLegalConfigRoute
  '/operations/dispatch': typeof adminOperationsDispatchRoute
  '/operations/returns': typeof adminOperationsReturnsRoute
  '/overview/analytics': typeof adminOverviewAnalyticsRoute
  '/overview/bi': typeof adminOverviewBiRoute
  '/overview/ops': typeof adminOverviewOpsRoute
  '/platform/experiments': typeof adminPlatformExperimentsRoute
  '/platform/flags': typeof adminPlatformFlagsRoute
  '/platform/integrations': typeof adminPlatformIntegrationsRoute
  '/platform/system': typeof adminPlatformSystemRoute
  '/staff/audit-log': typeof adminStaffAuditLogRoute
  '/staff/': typeof adminStaffIndexRoute
  '/catalog/categories/$slug': typeof adminCatalogCategoriesSlugRoute
  '/catalog/categories/new': typeof adminCatalogCategoriesNewRoute
  '/catalog/inventory/adjustments': typeof adminCatalogInventoryAdjustmentsRoute
  '/catalog/inventory/batches': typeof adminCatalogInventoryBatchesRoute
  '/catalog/products/bulk': typeof adminCatalogProductsBulkRoute
  '/catalog/products/new': typeof adminCatalogProductsNewRoute
  '/customers/broadcasts/new': typeof adminCustomersBroadcastsNewRoute
  '/customers/users/$userId': typeof adminCustomersUsersUserIdRoute
  '/finance/coupons/$couponId': typeof adminFinanceCouponsCouponIdRoute
  '/finance/coupons/new': typeof adminFinanceCouponsNewRoute
  '/finance/payments/$paymentId': typeof adminFinancePaymentsPaymentIdRoute
  '/finance/payments/failed': typeof adminFinancePaymentsFailedRoute
  '/finance/subscriptions/upcoming': typeof adminFinanceSubscriptionsUpcomingRoute
  '/legal/pages/$pageSlug': typeof adminLegalPagesPageSlugRoute
  '/operations/orders/$orderId': typeof adminOperationsOrdersOrderIdRoute
  '/operations/riders/$riderId': typeof adminOperationsRidersRiderIdRoute
  '/operations/tickets/$ticketId': typeof adminOperationsTicketsTicketIdRoute
  '/catalog/categories/': typeof adminCatalogCategoriesIndexRoute
  '/catalog/inventory/': typeof adminCatalogInventoryIndexRoute
  '/catalog/products/': typeof adminCatalogProductsIndexRoute
  '/customers/broadcasts/': typeof adminCustomersBroadcastsIndexRoute
  '/customers/users/': typeof adminCustomersUsersIndexRoute
  '/finance/coupons/': typeof adminFinanceCouponsIndexRoute
  '/finance/payments/': typeof adminFinancePaymentsIndexRoute
  '/finance/subscriptions/': typeof adminFinanceSubscriptionsIndexRoute
  '/legal/pages/': typeof adminLegalPagesIndexRoute
  '/operations/orders/': typeof adminOperationsOrdersIndexRoute
  '/operations/riders/': typeof adminOperationsRidersIndexRoute
  '/operations/tickets/': typeof adminOperationsTicketsIndexRoute
  '/catalog/products/$productId/images': typeof adminCatalogProductsProductIdImagesRoute
  '/catalog/products/$productId/stock': typeof adminCatalogProductsProductIdStockRoute
  '/catalog/products/$productId/': typeof adminCatalogProductsProductIdIndexRoute
}
export interface FileRoutesByTo {
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/': typeof adminIndexRoute
  '/catalog/brands': typeof adminCatalogBrandsRoute
  '/catalog/collections': typeof adminCatalogCollectionsRoute
  '/catalog/hubs': typeof adminCatalogHubsRoute
  '/catalog/merchandising': typeof adminCatalogMerchandisingRoute
  '/catalog/pricing': typeof adminCatalogPricingRoute
  '/customers/journeys': typeof adminCustomersJourneysRoute
  '/customers/reviews': typeof adminCustomersReviewsRoute
  '/customers/segments': typeof adminCustomersSegmentsRoute
  '/finance/campaigns': typeof adminFinanceCampaignsRoute
  '/finance/reconciliation': typeof adminFinanceReconciliationRoute
  '/finance/tax': typeof adminFinanceTaxRoute
  '/legal/banners': typeof adminLegalBannersRoute
  '/legal/config': typeof adminLegalConfigRoute
  '/operations/dispatch': typeof adminOperationsDispatchRoute
  '/operations/returns': typeof adminOperationsReturnsRoute
  '/overview/analytics': typeof adminOverviewAnalyticsRoute
  '/overview/bi': typeof adminOverviewBiRoute
  '/overview/ops': typeof adminOverviewOpsRoute
  '/platform/experiments': typeof adminPlatformExperimentsRoute
  '/platform/flags': typeof adminPlatformFlagsRoute
  '/platform/integrations': typeof adminPlatformIntegrationsRoute
  '/platform/system': typeof adminPlatformSystemRoute
  '/staff/audit-log': typeof adminStaffAuditLogRoute
  '/staff': typeof adminStaffIndexRoute
  '/catalog/categories/$slug': typeof adminCatalogCategoriesSlugRoute
  '/catalog/categories/new': typeof adminCatalogCategoriesNewRoute
  '/catalog/inventory/adjustments': typeof adminCatalogInventoryAdjustmentsRoute
  '/catalog/inventory/batches': typeof adminCatalogInventoryBatchesRoute
  '/catalog/products/bulk': typeof adminCatalogProductsBulkRoute
  '/catalog/products/new': typeof adminCatalogProductsNewRoute
  '/customers/broadcasts/new': typeof adminCustomersBroadcastsNewRoute
  '/customers/users/$userId': typeof adminCustomersUsersUserIdRoute
  '/finance/coupons/$couponId': typeof adminFinanceCouponsCouponIdRoute
  '/finance/coupons/new': typeof adminFinanceCouponsNewRoute
  '/finance/payments/$paymentId': typeof adminFinancePaymentsPaymentIdRoute
  '/finance/payments/failed': typeof adminFinancePaymentsFailedRoute
  '/finance/subscriptions/upcoming': typeof adminFinanceSubscriptionsUpcomingRoute
  '/legal/pages/$pageSlug': typeof adminLegalPagesPageSlugRoute
  '/operations/orders/$orderId': typeof adminOperationsOrdersOrderIdRoute
  '/operations/riders/$riderId': typeof adminOperationsRidersRiderIdRoute
  '/operations/tickets/$ticketId': typeof adminOperationsTicketsTicketIdRoute
  '/catalog/categories': typeof adminCatalogCategoriesIndexRoute
  '/catalog/inventory': typeof adminCatalogInventoryIndexRoute
  '/catalog/products': typeof adminCatalogProductsIndexRoute
  '/customers/broadcasts': typeof adminCustomersBroadcastsIndexRoute
  '/customers/users': typeof adminCustomersUsersIndexRoute
  '/finance/coupons': typeof adminFinanceCouponsIndexRoute
  '/finance/payments': typeof adminFinancePaymentsIndexRoute
  '/finance/subscriptions': typeof adminFinanceSubscriptionsIndexRoute
  '/legal/pages': typeof adminLegalPagesIndexRoute
  '/operations/orders': typeof adminOperationsOrdersIndexRoute
  '/operations/riders': typeof adminOperationsRidersIndexRoute
  '/operations/tickets': typeof adminOperationsTicketsIndexRoute
  '/catalog/products/$productId/images': typeof adminCatalogProductsProductIdImagesRoute
  '/catalog/products/$productId/stock': typeof adminCatalogProductsProductIdStockRoute
  '/catalog/products/$productId': typeof adminCatalogProductsProductIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(admin)': typeof adminLayoutRouteWithChildren
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/(admin)/': typeof adminIndexRoute
  '/(admin)/catalog/brands': typeof adminCatalogBrandsRoute
  '/(admin)/catalog/collections': typeof adminCatalogCollectionsRoute
  '/(admin)/catalog/hubs': typeof adminCatalogHubsRoute
  '/(admin)/catalog/merchandising': typeof adminCatalogMerchandisingRoute
  '/(admin)/catalog/pricing': typeof adminCatalogPricingRoute
  '/(admin)/customers/journeys': typeof adminCustomersJourneysRoute
  '/(admin)/customers/reviews': typeof adminCustomersReviewsRoute
  '/(admin)/customers/segments': typeof adminCustomersSegmentsRoute
  '/(admin)/finance/campaigns': typeof adminFinanceCampaignsRoute
  '/(admin)/finance/reconciliation': typeof adminFinanceReconciliationRoute
  '/(admin)/finance/tax': typeof adminFinanceTaxRoute
  '/(admin)/legal/banners': typeof adminLegalBannersRoute
  '/(admin)/legal/config': typeof adminLegalConfigRoute
  '/(admin)/operations/dispatch': typeof adminOperationsDispatchRoute
  '/(admin)/operations/returns': typeof adminOperationsReturnsRoute
  '/(admin)/overview/analytics': typeof adminOverviewAnalyticsRoute
  '/(admin)/overview/bi': typeof adminOverviewBiRoute
  '/(admin)/overview/ops': typeof adminOverviewOpsRoute
  '/(admin)/platform/experiments': typeof adminPlatformExperimentsRoute
  '/(admin)/platform/flags': typeof adminPlatformFlagsRoute
  '/(admin)/platform/integrations': typeof adminPlatformIntegrationsRoute
  '/(admin)/platform/system': typeof adminPlatformSystemRoute
  '/(admin)/staff/audit-log': typeof adminStaffAuditLogRoute
  '/(admin)/staff/': typeof adminStaffIndexRoute
  '/(admin)/catalog/categories/$slug': typeof adminCatalogCategoriesSlugRoute
  '/(admin)/catalog/categories/new': typeof adminCatalogCategoriesNewRoute
  '/(admin)/catalog/inventory/adjustments': typeof adminCatalogInventoryAdjustmentsRoute
  '/(admin)/catalog/inventory/batches': typeof adminCatalogInventoryBatchesRoute
  '/(admin)/catalog/products/bulk': typeof adminCatalogProductsBulkRoute
  '/(admin)/catalog/products/new': typeof adminCatalogProductsNewRoute
  '/(admin)/customers/broadcasts/new': typeof adminCustomersBroadcastsNewRoute
  '/(admin)/customers/users/$userId': typeof adminCustomersUsersUserIdRoute
  '/(admin)/finance/coupons/$couponId': typeof adminFinanceCouponsCouponIdRoute
  '/(admin)/finance/coupons/new': typeof adminFinanceCouponsNewRoute
  '/(admin)/finance/payments/$paymentId': typeof adminFinancePaymentsPaymentIdRoute
  '/(admin)/finance/payments/failed': typeof adminFinancePaymentsFailedRoute
  '/(admin)/finance/subscriptions/upcoming': typeof adminFinanceSubscriptionsUpcomingRoute
  '/(admin)/legal/pages/$pageSlug': typeof adminLegalPagesPageSlugRoute
  '/(admin)/operations/orders/$orderId': typeof adminOperationsOrdersOrderIdRoute
  '/(admin)/operations/riders/$riderId': typeof adminOperationsRidersRiderIdRoute
  '/(admin)/operations/tickets/$ticketId': typeof adminOperationsTicketsTicketIdRoute
  '/(admin)/catalog/categories/': typeof adminCatalogCategoriesIndexRoute
  '/(admin)/catalog/inventory/': typeof adminCatalogInventoryIndexRoute
  '/(admin)/catalog/products/': typeof adminCatalogProductsIndexRoute
  '/(admin)/customers/broadcasts/': typeof adminCustomersBroadcastsIndexRoute
  '/(admin)/customers/users/': typeof adminCustomersUsersIndexRoute
  '/(admin)/finance/coupons/': typeof adminFinanceCouponsIndexRoute
  '/(admin)/finance/payments/': typeof adminFinancePaymentsIndexRoute
  '/(admin)/finance/subscriptions/': typeof adminFinanceSubscriptionsIndexRoute
  '/(admin)/legal/pages/': typeof adminLegalPagesIndexRoute
  '/(admin)/operations/orders/': typeof adminOperationsOrdersIndexRoute
  '/(admin)/operations/riders/': typeof adminOperationsRidersIndexRoute
  '/(admin)/operations/tickets/': typeof adminOperationsTicketsIndexRoute
  '/(admin)/catalog/products/$productId/images': typeof adminCatalogProductsProductIdImagesRoute
  '/(admin)/catalog/products/$productId/stock': typeof adminCatalogProductsProductIdStockRoute
  '/(admin)/catalog/products/$productId/': typeof adminCatalogProductsProductIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/forbidden'
    | '/login'
    | '/'
    | '/catalog/brands'
    | '/catalog/collections'
    | '/catalog/hubs'
    | '/catalog/merchandising'
    | '/catalog/pricing'
    | '/customers/journeys'
    | '/customers/reviews'
    | '/customers/segments'
    | '/finance/campaigns'
    | '/finance/reconciliation'
    | '/finance/tax'
    | '/legal/banners'
    | '/legal/config'
    | '/operations/dispatch'
    | '/operations/returns'
    | '/overview/analytics'
    | '/overview/bi'
    | '/overview/ops'
    | '/platform/experiments'
    | '/platform/flags'
    | '/platform/integrations'
    | '/platform/system'
    | '/staff/audit-log'
    | '/staff/'
    | '/catalog/categories/$slug'
    | '/catalog/categories/new'
    | '/catalog/inventory/adjustments'
    | '/catalog/inventory/batches'
    | '/catalog/products/bulk'
    | '/catalog/products/new'
    | '/customers/broadcasts/new'
    | '/customers/users/$userId'
    | '/finance/coupons/$couponId'
    | '/finance/coupons/new'
    | '/finance/payments/$paymentId'
    | '/finance/payments/failed'
    | '/finance/subscriptions/upcoming'
    | '/legal/pages/$pageSlug'
    | '/operations/orders/$orderId'
    | '/operations/riders/$riderId'
    | '/operations/tickets/$ticketId'
    | '/catalog/categories/'
    | '/catalog/inventory/'
    | '/catalog/products/'
    | '/customers/broadcasts/'
    | '/customers/users/'
    | '/finance/coupons/'
    | '/finance/payments/'
    | '/finance/subscriptions/'
    | '/legal/pages/'
    | '/operations/orders/'
    | '/operations/riders/'
    | '/operations/tickets/'
    | '/catalog/products/$productId/images'
    | '/catalog/products/$productId/stock'
    | '/catalog/products/$productId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forbidden'
    | '/login'
    | '/'
    | '/catalog/brands'
    | '/catalog/collections'
    | '/catalog/hubs'
    | '/catalog/merchandising'
    | '/catalog/pricing'
    | '/customers/journeys'
    | '/customers/reviews'
    | '/customers/segments'
    | '/finance/campaigns'
    | '/finance/reconciliation'
    | '/finance/tax'
    | '/legal/banners'
    | '/legal/config'
    | '/operations/dispatch'
    | '/operations/returns'
    | '/overview/analytics'
    | '/overview/bi'
    | '/overview/ops'
    | '/platform/experiments'
    | '/platform/flags'
    | '/platform/integrations'
    | '/platform/system'
    | '/staff/audit-log'
    | '/staff'
    | '/catalog/categories/$slug'
    | '/catalog/categories/new'
    | '/catalog/inventory/adjustments'
    | '/catalog/inventory/batches'
    | '/catalog/products/bulk'
    | '/catalog/products/new'
    | '/customers/broadcasts/new'
    | '/customers/users/$userId'
    | '/finance/coupons/$couponId'
    | '/finance/coupons/new'
    | '/finance/payments/$paymentId'
    | '/finance/payments/failed'
    | '/finance/subscriptions/upcoming'
    | '/legal/pages/$pageSlug'
    | '/operations/orders/$orderId'
    | '/operations/riders/$riderId'
    | '/operations/tickets/$ticketId'
    | '/catalog/categories'
    | '/catalog/inventory'
    | '/catalog/products'
    | '/customers/broadcasts'
    | '/customers/users'
    | '/finance/coupons'
    | '/finance/payments'
    | '/finance/subscriptions'
    | '/legal/pages'
    | '/operations/orders'
    | '/operations/riders'
    | '/operations/tickets'
    | '/catalog/products/$productId/images'
    | '/catalog/products/$productId/stock'
    | '/catalog/products/$productId'
  id:
    | '__root__'
    | '/(admin)'
    | '/forbidden'
    | '/login'
    | '/(admin)/'
    | '/(admin)/catalog/brands'
    | '/(admin)/catalog/collections'
    | '/(admin)/catalog/hubs'
    | '/(admin)/catalog/merchandising'
    | '/(admin)/catalog/pricing'
    | '/(admin)/customers/journeys'
    | '/(admin)/customers/reviews'
    | '/(admin)/customers/segments'
    | '/(admin)/finance/campaigns'
    | '/(admin)/finance/reconciliation'
    | '/(admin)/finance/tax'
    | '/(admin)/legal/banners'
    | '/(admin)/legal/config'
    | '/(admin)/operations/dispatch'
    | '/(admin)/operations/returns'
    | '/(admin)/overview/analytics'
    | '/(admin)/overview/bi'
    | '/(admin)/overview/ops'
    | '/(admin)/platform/experiments'
    | '/(admin)/platform/flags'
    | '/(admin)/platform/integrations'
    | '/(admin)/platform/system'
    | '/(admin)/staff/audit-log'
    | '/(admin)/staff/'
    | '/(admin)/catalog/categories/$slug'
    | '/(admin)/catalog/categories/new'
    | '/(admin)/catalog/inventory/adjustments'
    | '/(admin)/catalog/inventory/batches'
    | '/(admin)/catalog/products/bulk'
    | '/(admin)/catalog/products/new'
    | '/(admin)/customers/broadcasts/new'
    | '/(admin)/customers/users/$userId'
    | '/(admin)/finance/coupons/$couponId'
    | '/(admin)/finance/coupons/new'
    | '/(admin)/finance/payments/$paymentId'
    | '/(admin)/finance/payments/failed'
    | '/(admin)/finance/subscriptions/upcoming'
    | '/(admin)/legal/pages/$pageSlug'
    | '/(admin)/operations/orders/$orderId'
    | '/(admin)/operations/riders/$riderId'
    | '/(admin)/operations/tickets/$ticketId'
    | '/(admin)/catalog/categories/'
    | '/(admin)/catalog/inventory/'
    | '/(admin)/catalog/products/'
    | '/(admin)/customers/broadcasts/'
    | '/(admin)/customers/users/'
    | '/(admin)/finance/coupons/'
    | '/(admin)/finance/payments/'
    | '/(admin)/finance/subscriptions/'
    | '/(admin)/legal/pages/'
    | '/(admin)/operations/orders/'
    | '/(admin)/operations/riders/'
    | '/(admin)/operations/tickets/'
    | '/(admin)/catalog/products/$productId/images'
    | '/(admin)/catalog/products/$productId/stock'
    | '/(admin)/catalog/products/$productId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  adminLayoutRoute: typeof adminLayoutRouteWithChildren
  ForbiddenRoute: typeof ForbiddenRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)': {
      id: '/(admin)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof adminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/': {
      id: '/(admin)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof adminIndexRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/staff/': {
      id: '/(admin)/staff/'
      path: '/staff'
      fullPath: '/staff/'
      preLoaderRoute: typeof adminStaffIndexRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/staff/audit-log': {
      id: '/(admin)/staff/audit-log'
      path: '/staff/audit-log'
      fullPath: '/staff/audit-log'
      preLoaderRoute: typeof adminStaffAuditLogRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/platform/system': {
      id: '/(admin)/platform/system'
      path: '/platform/system'
      fullPath: '/platform/system'
      preLoaderRoute: typeof adminPlatformSystemRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/platform/integrations': {
      id: '/(admin)/platform/integrations'
      path: '/platform/integrations'
      fullPath: '/platform/integrations'
      preLoaderRoute: typeof adminPlatformIntegrationsRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/platform/flags': {
      id: '/(admin)/platform/flags'
      path: '/platform/flags'
      fullPath: '/platform/flags'
      preLoaderRoute: typeof adminPlatformFlagsRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/platform/experiments': {
      id: '/(admin)/platform/experiments'
      path: '/platform/experiments'
      fullPath: '/platform/experiments'
      preLoaderRoute: typeof adminPlatformExperimentsRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/overview/ops': {
      id: '/(admin)/overview/ops'
      path: '/overview/ops'
      fullPath: '/overview/ops'
      preLoaderRoute: typeof adminOverviewOpsRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/overview/bi': {
      id: '/(admin)/overview/bi'
      path: '/overview/bi'
      fullPath: '/overview/bi'
      preLoaderRoute: typeof adminOverviewBiRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/overview/analytics': {
      id: '/(admin)/overview/analytics'
      path: '/overview/analytics'
      fullPath: '/overview/analytics'
      preLoaderRoute: typeof adminOverviewAnalyticsRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/operations/returns': {
      id: '/(admin)/operations/returns'
      path: '/operations/returns'
      fullPath: '/operations/returns'
      preLoaderRoute: typeof adminOperationsReturnsRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/operations/dispatch': {
      id: '/(admin)/operations/dispatch'
      path: '/operations/dispatch'
      fullPath: '/operations/dispatch'
      preLoaderRoute: typeof adminOperationsDispatchRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/legal/config': {
      id: '/(admin)/legal/config'
      path: '/legal/config'
      fullPath: '/legal/config'
      preLoaderRoute: typeof adminLegalConfigRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/legal/banners': {
      id: '/(admin)/legal/banners'
      path: '/legal/banners'
      fullPath: '/legal/banners'
      preLoaderRoute: typeof adminLegalBannersRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/finance/tax': {
      id: '/(admin)/finance/tax'
      path: '/finance/tax'
      fullPath: '/finance/tax'
      preLoaderRoute: typeof adminFinanceTaxRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/finance/reconciliation': {
      id: '/(admin)/finance/reconciliation'
      path: '/finance/reconciliation'
      fullPath: '/finance/reconciliation'
      preLoaderRoute: typeof adminFinanceReconciliationRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/finance/campaigns': {
      id: '/(admin)/finance/campaigns'
      path: '/finance/campaigns'
      fullPath: '/finance/campaigns'
      preLoaderRoute: typeof adminFinanceCampaignsRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/customers/segments': {
      id: '/(admin)/customers/segments'
      path: '/customers/segments'
      fullPath: '/customers/segments'
      preLoaderRoute: typeof adminCustomersSegmentsRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/customers/reviews': {
      id: '/(admin)/customers/reviews'
      path: '/customers/reviews'
      fullPath: '/customers/reviews'
      preLoaderRoute: typeof adminCustomersReviewsRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/customers/journeys': {
      id: '/(admin)/customers/journeys'
      path: '/customers/journeys'
      fullPath: '/customers/journeys'
      preLoaderRoute: typeof adminCustomersJourneysRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/catalog/pricing': {
      id: '/(admin)/catalog/pricing'
      path: '/catalog/pricing'
      fullPath: '/catalog/pricing'
      preLoaderRoute: typeof adminCatalogPricingRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/catalog/merchandising': {
      id: '/(admin)/catalog/merchandising'
      path: '/catalog/merchandising'
      fullPath: '/catalog/merchandising'
      preLoaderRoute: typeof adminCatalogMerchandisingRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/catalog/hubs': {
      id: '/(admin)/catalog/hubs'
      path: '/catalog/hubs'
      fullPath: '/catalog/hubs'
      preLoaderRoute: typeof adminCatalogHubsRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/catalog/collections': {
      id: '/(admin)/catalog/collections'
      path: '/catalog/collections'
      fullPath: '/catalog/collections'
      preLoaderRoute: typeof adminCatalogCollectionsRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/catalog/brands': {
      id: '/(admin)/catalog/brands'
      path: '/catalog/brands'
      fullPath: '/catalog/brands'
      preLoaderRoute: typeof adminCatalogBrandsRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/operations/tickets/': {
      id: '/(admin)/operations/tickets/'
      path: '/operations/tickets'
      fullPath: '/operations/tickets/'
      preLoaderRoute: typeof adminOperationsTicketsIndexRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/operations/riders/': {
      id: '/(admin)/operations/riders/'
      path: '/operations/riders'
      fullPath: '/operations/riders/'
      preLoaderRoute: typeof adminOperationsRidersIndexRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/operations/orders/': {
      id: '/(admin)/operations/orders/'
      path: '/operations/orders'
      fullPath: '/operations/orders/'
      preLoaderRoute: typeof adminOperationsOrdersIndexRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/legal/pages/': {
      id: '/(admin)/legal/pages/'
      path: '/legal/pages'
      fullPath: '/legal/pages/'
      preLoaderRoute: typeof adminLegalPagesIndexRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/finance/subscriptions/': {
      id: '/(admin)/finance/subscriptions/'
      path: '/finance/subscriptions'
      fullPath: '/finance/subscriptions/'
      preLoaderRoute: typeof adminFinanceSubscriptionsIndexRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/finance/payments/': {
      id: '/(admin)/finance/payments/'
      path: '/finance/payments'
      fullPath: '/finance/payments/'
      preLoaderRoute: typeof adminFinancePaymentsIndexRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/finance/coupons/': {
      id: '/(admin)/finance/coupons/'
      path: '/finance/coupons'
      fullPath: '/finance/coupons/'
      preLoaderRoute: typeof adminFinanceCouponsIndexRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/customers/users/': {
      id: '/(admin)/customers/users/'
      path: '/customers/users'
      fullPath: '/customers/users/'
      preLoaderRoute: typeof adminCustomersUsersIndexRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/customers/broadcasts/': {
      id: '/(admin)/customers/broadcasts/'
      path: '/customers/broadcasts'
      fullPath: '/customers/broadcasts/'
      preLoaderRoute: typeof adminCustomersBroadcastsIndexRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/catalog/products/': {
      id: '/(admin)/catalog/products/'
      path: '/catalog/products'
      fullPath: '/catalog/products/'
      preLoaderRoute: typeof adminCatalogProductsIndexRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/catalog/inventory/': {
      id: '/(admin)/catalog/inventory/'
      path: '/catalog/inventory'
      fullPath: '/catalog/inventory/'
      preLoaderRoute: typeof adminCatalogInventoryIndexRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/catalog/categories/': {
      id: '/(admin)/catalog/categories/'
      path: '/catalog/categories'
      fullPath: '/catalog/categories/'
      preLoaderRoute: typeof adminCatalogCategoriesIndexRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/operations/tickets/$ticketId': {
      id: '/(admin)/operations/tickets/$ticketId'
      path: '/operations/tickets/$ticketId'
      fullPath: '/operations/tickets/$ticketId'
      preLoaderRoute: typeof adminOperationsTicketsTicketIdRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/operations/riders/$riderId': {
      id: '/(admin)/operations/riders/$riderId'
      path: '/operations/riders/$riderId'
      fullPath: '/operations/riders/$riderId'
      preLoaderRoute: typeof adminOperationsRidersRiderIdRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/operations/orders/$orderId': {
      id: '/(admin)/operations/orders/$orderId'
      path: '/operations/orders/$orderId'
      fullPath: '/operations/orders/$orderId'
      preLoaderRoute: typeof adminOperationsOrdersOrderIdRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/legal/pages/$pageSlug': {
      id: '/(admin)/legal/pages/$pageSlug'
      path: '/legal/pages/$pageSlug'
      fullPath: '/legal/pages/$pageSlug'
      preLoaderRoute: typeof adminLegalPagesPageSlugRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/finance/subscriptions/upcoming': {
      id: '/(admin)/finance/subscriptions/upcoming'
      path: '/finance/subscriptions/upcoming'
      fullPath: '/finance/subscriptions/upcoming'
      preLoaderRoute: typeof adminFinanceSubscriptionsUpcomingRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/finance/payments/failed': {
      id: '/(admin)/finance/payments/failed'
      path: '/finance/payments/failed'
      fullPath: '/finance/payments/failed'
      preLoaderRoute: typeof adminFinancePaymentsFailedRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/finance/payments/$paymentId': {
      id: '/(admin)/finance/payments/$paymentId'
      path: '/finance/payments/$paymentId'
      fullPath: '/finance/payments/$paymentId'
      preLoaderRoute: typeof adminFinancePaymentsPaymentIdRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/finance/coupons/new': {
      id: '/(admin)/finance/coupons/new'
      path: '/finance/coupons/new'
      fullPath: '/finance/coupons/new'
      preLoaderRoute: typeof adminFinanceCouponsNewRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/finance/coupons/$couponId': {
      id: '/(admin)/finance/coupons/$couponId'
      path: '/finance/coupons/$couponId'
      fullPath: '/finance/coupons/$couponId'
      preLoaderRoute: typeof adminFinanceCouponsCouponIdRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/customers/users/$userId': {
      id: '/(admin)/customers/users/$userId'
      path: '/customers/users/$userId'
      fullPath: '/customers/users/$userId'
      preLoaderRoute: typeof adminCustomersUsersUserIdRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/customers/broadcasts/new': {
      id: '/(admin)/customers/broadcasts/new'
      path: '/customers/broadcasts/new'
      fullPath: '/customers/broadcasts/new'
      preLoaderRoute: typeof adminCustomersBroadcastsNewRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/catalog/products/new': {
      id: '/(admin)/catalog/products/new'
      path: '/catalog/products/new'
      fullPath: '/catalog/products/new'
      preLoaderRoute: typeof adminCatalogProductsNewRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/catalog/products/bulk': {
      id: '/(admin)/catalog/products/bulk'
      path: '/catalog/products/bulk'
      fullPath: '/catalog/products/bulk'
      preLoaderRoute: typeof adminCatalogProductsBulkRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/catalog/inventory/batches': {
      id: '/(admin)/catalog/inventory/batches'
      path: '/catalog/inventory/batches'
      fullPath: '/catalog/inventory/batches'
      preLoaderRoute: typeof adminCatalogInventoryBatchesRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/catalog/inventory/adjustments': {
      id: '/(admin)/catalog/inventory/adjustments'
      path: '/catalog/inventory/adjustments'
      fullPath: '/catalog/inventory/adjustments'
      preLoaderRoute: typeof adminCatalogInventoryAdjustmentsRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/catalog/categories/new': {
      id: '/(admin)/catalog/categories/new'
      path: '/catalog/categories/new'
      fullPath: '/catalog/categories/new'
      preLoaderRoute: typeof adminCatalogCategoriesNewRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/catalog/categories/$slug': {
      id: '/(admin)/catalog/categories/$slug'
      path: '/catalog/categories/$slug'
      fullPath: '/catalog/categories/$slug'
      preLoaderRoute: typeof adminCatalogCategoriesSlugRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/catalog/products/$productId/': {
      id: '/(admin)/catalog/products/$productId/'
      path: '/catalog/products/$productId'
      fullPath: '/catalog/products/$productId/'
      preLoaderRoute: typeof adminCatalogProductsProductIdIndexRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/catalog/products/$productId/stock': {
      id: '/(admin)/catalog/products/$productId/stock'
      path: '/catalog/products/$productId/stock'
      fullPath: '/catalog/products/$productId/stock'
      preLoaderRoute: typeof adminCatalogProductsProductIdStockRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/catalog/products/$productId/images': {
      id: '/(admin)/catalog/products/$productId/images'
      path: '/catalog/products/$productId/images'
      fullPath: '/catalog/products/$productId/images'
      preLoaderRoute: typeof adminCatalogProductsProductIdImagesRouteImport
      parentRoute: typeof adminLayoutRoute
    }
  }
}

interface adminLayoutRouteChildren {
  adminIndexRoute: typeof adminIndexRoute
  adminCatalogBrandsRoute: typeof adminCatalogBrandsRoute
  adminCatalogCollectionsRoute: typeof adminCatalogCollectionsRoute
  adminCatalogHubsRoute: typeof adminCatalogHubsRoute
  adminCatalogMerchandisingRoute: typeof adminCatalogMerchandisingRoute
  adminCatalogPricingRoute: typeof adminCatalogPricingRoute
  adminCustomersJourneysRoute: typeof adminCustomersJourneysRoute
  adminCustomersReviewsRoute: typeof adminCustomersReviewsRoute
  adminCustomersSegmentsRoute: typeof adminCustomersSegmentsRoute
  adminFinanceCampaignsRoute: typeof adminFinanceCampaignsRoute
  adminFinanceReconciliationRoute: typeof adminFinanceReconciliationRoute
  adminFinanceTaxRoute: typeof adminFinanceTaxRoute
  adminLegalBannersRoute: typeof adminLegalBannersRoute
  adminLegalConfigRoute: typeof adminLegalConfigRoute
  adminOperationsDispatchRoute: typeof adminOperationsDispatchRoute
  adminOperationsReturnsRoute: typeof adminOperationsReturnsRoute
  adminOverviewAnalyticsRoute: typeof adminOverviewAnalyticsRoute
  adminOverviewBiRoute: typeof adminOverviewBiRoute
  adminOverviewOpsRoute: typeof adminOverviewOpsRoute
  adminPlatformExperimentsRoute: typeof adminPlatformExperimentsRoute
  adminPlatformFlagsRoute: typeof adminPlatformFlagsRoute
  adminPlatformIntegrationsRoute: typeof adminPlatformIntegrationsRoute
  adminPlatformSystemRoute: typeof adminPlatformSystemRoute
  adminStaffAuditLogRoute: typeof adminStaffAuditLogRoute
  adminStaffIndexRoute: typeof adminStaffIndexRoute
  adminCatalogCategoriesSlugRoute: typeof adminCatalogCategoriesSlugRoute
  adminCatalogCategoriesNewRoute: typeof adminCatalogCategoriesNewRoute
  adminCatalogInventoryAdjustmentsRoute: typeof adminCatalogInventoryAdjustmentsRoute
  adminCatalogInventoryBatchesRoute: typeof adminCatalogInventoryBatchesRoute
  adminCatalogProductsBulkRoute: typeof adminCatalogProductsBulkRoute
  adminCatalogProductsNewRoute: typeof adminCatalogProductsNewRoute
  adminCustomersBroadcastsNewRoute: typeof adminCustomersBroadcastsNewRoute
  adminCustomersUsersUserIdRoute: typeof adminCustomersUsersUserIdRoute
  adminFinanceCouponsCouponIdRoute: typeof adminFinanceCouponsCouponIdRoute
  adminFinanceCouponsNewRoute: typeof adminFinanceCouponsNewRoute
  adminFinancePaymentsPaymentIdRoute: typeof adminFinancePaymentsPaymentIdRoute
  adminFinancePaymentsFailedRoute: typeof adminFinancePaymentsFailedRoute
  adminFinanceSubscriptionsUpcomingRoute: typeof adminFinanceSubscriptionsUpcomingRoute
  adminLegalPagesPageSlugRoute: typeof adminLegalPagesPageSlugRoute
  adminOperationsOrdersOrderIdRoute: typeof adminOperationsOrdersOrderIdRoute
  adminOperationsRidersRiderIdRoute: typeof adminOperationsRidersRiderIdRoute
  adminOperationsTicketsTicketIdRoute: typeof adminOperationsTicketsTicketIdRoute
  adminCatalogCategoriesIndexRoute: typeof adminCatalogCategoriesIndexRoute
  adminCatalogInventoryIndexRoute: typeof adminCatalogInventoryIndexRoute
  adminCatalogProductsIndexRoute: typeof adminCatalogProductsIndexRoute
  adminCustomersBroadcastsIndexRoute: typeof adminCustomersBroadcastsIndexRoute
  adminCustomersUsersIndexRoute: typeof adminCustomersUsersIndexRoute
  adminFinanceCouponsIndexRoute: typeof adminFinanceCouponsIndexRoute
  adminFinancePaymentsIndexRoute: typeof adminFinancePaymentsIndexRoute
  adminFinanceSubscriptionsIndexRoute: typeof adminFinanceSubscriptionsIndexRoute
  adminLegalPagesIndexRoute: typeof adminLegalPagesIndexRoute
  adminOperationsOrdersIndexRoute: typeof adminOperationsOrdersIndexRoute
  adminOperationsRidersIndexRoute: typeof adminOperationsRidersIndexRoute
  adminOperationsTicketsIndexRoute: typeof adminOperationsTicketsIndexRoute
  adminCatalogProductsProductIdImagesRoute: typeof adminCatalogProductsProductIdImagesRoute
  adminCatalogProductsProductIdStockRoute: typeof adminCatalogProductsProductIdStockRoute
  adminCatalogProductsProductIdIndexRoute: typeof adminCatalogProductsProductIdIndexRoute
}

const adminLayoutRouteChildren: adminLayoutRouteChildren = {
  adminIndexRoute: adminIndexRoute,
  adminCatalogBrandsRoute: adminCatalogBrandsRoute,
  adminCatalogCollectionsRoute: adminCatalogCollectionsRoute,
  adminCatalogHubsRoute: adminCatalogHubsRoute,
  adminCatalogMerchandisingRoute: adminCatalogMerchandisingRoute,
  adminCatalogPricingRoute: adminCatalogPricingRoute,
  adminCustomersJourneysRoute: adminCustomersJourneysRoute,
  adminCustomersReviewsRoute: adminCustomersReviewsRoute,
  adminCustomersSegmentsRoute: adminCustomersSegmentsRoute,
  adminFinanceCampaignsRoute: adminFinanceCampaignsRoute,
  adminFinanceReconciliationRoute: adminFinanceReconciliationRoute,
  adminFinanceTaxRoute: adminFinanceTaxRoute,
  adminLegalBannersRoute: adminLegalBannersRoute,
  adminLegalConfigRoute: adminLegalConfigRoute,
  adminOperationsDispatchRoute: adminOperationsDispatchRoute,
  adminOperationsReturnsRoute: adminOperationsReturnsRoute,
  adminOverviewAnalyticsRoute: adminOverviewAnalyticsRoute,
  adminOverviewBiRoute: adminOverviewBiRoute,
  adminOverviewOpsRoute: adminOverviewOpsRoute,
  adminPlatformExperimentsRoute: adminPlatformExperimentsRoute,
  adminPlatformFlagsRoute: adminPlatformFlagsRoute,
  adminPlatformIntegrationsRoute: adminPlatformIntegrationsRoute,
  adminPlatformSystemRoute: adminPlatformSystemRoute,
  adminStaffAuditLogRoute: adminStaffAuditLogRoute,
  adminStaffIndexRoute: adminStaffIndexRoute,
  adminCatalogCategoriesSlugRoute: adminCatalogCategoriesSlugRoute,
  adminCatalogCategoriesNewRoute: adminCatalogCategoriesNewRoute,
  adminCatalogInventoryAdjustmentsRoute: adminCatalogInventoryAdjustmentsRoute,
  adminCatalogInventoryBatchesRoute: adminCatalogInventoryBatchesRoute,
  adminCatalogProductsBulkRoute: adminCatalogProductsBulkRoute,
  adminCatalogProductsNewRoute: adminCatalogProductsNewRoute,
  adminCustomersBroadcastsNewRoute: adminCustomersBroadcastsNewRoute,
  adminCustomersUsersUserIdRoute: adminCustomersUsersUserIdRoute,
  adminFinanceCouponsCouponIdRoute: adminFinanceCouponsCouponIdRoute,
  adminFinanceCouponsNewRoute: adminFinanceCouponsNewRoute,
  adminFinancePaymentsPaymentIdRoute: adminFinancePaymentsPaymentIdRoute,
  adminFinancePaymentsFailedRoute: adminFinancePaymentsFailedRoute,
  adminFinanceSubscriptionsUpcomingRoute:
    adminFinanceSubscriptionsUpcomingRoute,
  adminLegalPagesPageSlugRoute: adminLegalPagesPageSlugRoute,
  adminOperationsOrdersOrderIdRoute: adminOperationsOrdersOrderIdRoute,
  adminOperationsRidersRiderIdRoute: adminOperationsRidersRiderIdRoute,
  adminOperationsTicketsTicketIdRoute: adminOperationsTicketsTicketIdRoute,
  adminCatalogCategoriesIndexRoute: adminCatalogCategoriesIndexRoute,
  adminCatalogInventoryIndexRoute: adminCatalogInventoryIndexRoute,
  adminCatalogProductsIndexRoute: adminCatalogProductsIndexRoute,
  adminCustomersBroadcastsIndexRoute: adminCustomersBroadcastsIndexRoute,
  adminCustomersUsersIndexRoute: adminCustomersUsersIndexRoute,
  adminFinanceCouponsIndexRoute: adminFinanceCouponsIndexRoute,
  adminFinancePaymentsIndexRoute: adminFinancePaymentsIndexRoute,
  adminFinanceSubscriptionsIndexRoute: adminFinanceSubscriptionsIndexRoute,
  adminLegalPagesIndexRoute: adminLegalPagesIndexRoute,
  adminOperationsOrdersIndexRoute: adminOperationsOrdersIndexRoute,
  adminOperationsRidersIndexRoute: adminOperationsRidersIndexRoute,
  adminOperationsTicketsIndexRoute: adminOperationsTicketsIndexRoute,
  adminCatalogProductsProductIdImagesRoute:
    adminCatalogProductsProductIdImagesRoute,
  adminCatalogProductsProductIdStockRoute:
    adminCatalogProductsProductIdStockRoute,
  adminCatalogProductsProductIdIndexRoute:
    adminCatalogProductsProductIdIndexRoute,
}

const adminLayoutRouteWithChildren = adminLayoutRoute._addFileChildren(
  adminLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  adminLayoutRoute: adminLayoutRouteWithChildren,
  ForbiddenRoute: ForbiddenRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
